// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: activity_logs.sql

package db

import (
	"context"
	"database/sql"
)

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO activity_logs (actor_type, actor_id, action, description, ip) VALUES (?, ?, ?, ?, ?)
`

type CreateActivityLogParams struct {
	ActorType   string
	ActorID     int64
	Action      string
	Description string
	Ip          string
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.ExecContext(ctx, createActivityLog,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.Description,
		arg.Ip,
	)
	return err
}

const deleteActivityLogsBefore = `-- name: DeleteActivityLogsBefore :execrows
DELETE FROM activity_logs WHERE created_at < ?
`

func (q *Queries) DeleteActivityLogsBefore(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteActivityLogsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMessageLogsBefore = `-- name: DeleteMessageLogsBefore :execrows
DELETE FROM message_logs WHERE created_at < ?
`

func (q *Queries) DeleteMessageLogsBefore(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMessageLogsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRadiusSessionsClosedBefore = `-- name: DeleteRadiusSessionsClosedBefore :execrows
DELETE FROM radius_sessions WHERE stopped_at IS NOT NULL AND stopped_at < ?
`

// Open sessions (stopped_at NULL) are never deleted.
func (q *Queries) DeleteRadiusSessionsClosedBefore(ctx context.Context, stoppedAt sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRadiusSessionsClosedBefore, stoppedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT id, actor_type, actor_id, "action", description, ip, created_at FROM activity_logs ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListActivityLogsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.Description,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchActivityLogs = `-- name: SearchActivityLogs :many
SELECT id, actor_type, actor_id, "action", description, ip, created_at FROM activity_logs
WHERE action LIKE '%' || CAST(?1 AS TEXT) || '%' OR description LIKE '%' || CAST(?1 AS TEXT) || '%'
ORDER BY id DESC LIMIT ?3 OFFSET ?2
`

type SearchActivityLogsParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchActivityLogs(ctx context.Context, arg SearchActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, searchActivityLogs, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.Description,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
