// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: admins.sql

package db

import (
	"context"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (username, fullname, password_hash, role)
VALUES (?, ?, ?, ?)
RETURNING id, username, fullname, password_hash, role, status, last_login_at, created_at
`

type CreateAdminParams struct {
	Username     string
	Fullname     string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createAdmin,
		arg.Username,
		arg.Fullname,
		arg.PasswordHash,
		arg.Role,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Fullname,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, username, fullname, password_hash, role, status, last_login_at, created_at FROM admins WHERE id = ? LIMIT 1
`

func (q *Queries) GetAdmin(ctx context.Context, id int64) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdmin, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Fullname,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, fullname, password_hash, role, status, last_login_at, created_at FROM admins WHERE username = ? LIMIT 1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Fullname,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchAdminLogin = `-- name: TouchAdminLogin :exec
UPDATE admins SET last_login_at = unixepoch() WHERE id = ?
`

func (q *Queries) TouchAdminLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchAdminLogin, id)
	return err
}
