// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bandwidths.sql

package db

import (
	"context"
)

const createBandwidth = `-- name: CreateBandwidth :one
INSERT INTO bandwidths (name, rate_down, rate_down_unit, rate_up, rate_up_unit, burst)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, rate_down, rate_down_unit, rate_up, rate_up_unit, burst
`

type CreateBandwidthParams struct {
	Name         string
	RateDown     int64
	RateDownUnit string
	RateUp       int64
	RateUpUnit   string
	Burst        string
}

func (q *Queries) CreateBandwidth(ctx context.Context, arg CreateBandwidthParams) (Bandwidth, error) {
	row := q.db.QueryRowContext(ctx, createBandwidth,
		arg.Name,
		arg.RateDown,
		arg.RateDownUnit,
		arg.RateUp,
		arg.RateUpUnit,
		arg.Burst,
	)
	var i Bandwidth
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RateDown,
		&i.RateDownUnit,
		&i.RateUp,
		&i.RateUpUnit,
		&i.Burst,
	)
	return i, err
}

const deleteBandwidth = `-- name: DeleteBandwidth :exec
DELETE FROM bandwidths WHERE id = ?
`

func (q *Queries) DeleteBandwidth(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBandwidth, id)
	return err
}

const getBandwidth = `-- name: GetBandwidth :one
SELECT id, name, rate_down, rate_down_unit, rate_up, rate_up_unit, burst FROM bandwidths WHERE id = ?
`

func (q *Queries) GetBandwidth(ctx context.Context, id int64) (Bandwidth, error) {
	row := q.db.QueryRowContext(ctx, getBandwidth, id)
	var i Bandwidth
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RateDown,
		&i.RateDownUnit,
		&i.RateUp,
		&i.RateUpUnit,
		&i.Burst,
	)
	return i, err
}

const listBandwidths = `-- name: ListBandwidths :many
SELECT id, name, rate_down, rate_down_unit, rate_up, rate_up_unit, burst FROM bandwidths ORDER BY name LIMIT ? OFFSET ?
`

type ListBandwidthsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListBandwidths(ctx context.Context, arg ListBandwidthsParams) ([]Bandwidth, error) {
	rows, err := q.db.QueryContext(ctx, listBandwidths, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bandwidth
	for rows.Next() {
		var i Bandwidth
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RateDown,
			&i.RateDownUnit,
			&i.RateUp,
			&i.RateUpUnit,
			&i.Burst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBandwidths = `-- name: SearchBandwidths :many
SELECT id, name, rate_down, rate_down_unit, rate_up, rate_up_unit, burst FROM bandwidths WHERE name LIKE '%' || CAST(?1 AS TEXT) || '%' ORDER BY name LIMIT ?3 OFFSET ?2
`

type SearchBandwidthsParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchBandwidths(ctx context.Context, arg SearchBandwidthsParams) ([]Bandwidth, error) {
	rows, err := q.db.QueryContext(ctx, searchBandwidths, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bandwidth
	for rows.Next() {
		var i Bandwidth
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RateDown,
			&i.RateDownUnit,
			&i.RateUp,
			&i.RateUpUnit,
			&i.Burst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBandwidth = `-- name: UpdateBandwidth :exec
UPDATE bandwidths SET name = ?, rate_down = ?, rate_down_unit = ?, rate_up = ?, rate_up_unit = ?, burst = ?
WHERE id = ?
`

type UpdateBandwidthParams struct {
	Name         string
	RateDown     int64
	RateDownUnit string
	RateUp       int64
	RateUpUnit   string
	Burst        string
	ID           int64
}

func (q *Queries) UpdateBandwidth(ctx context.Context, arg UpdateBandwidthParams) error {
	_, err := q.db.ExecContext(ctx, updateBandwidth,
		arg.Name,
		arg.RateDown,
		arg.RateDownUnit,
		arg.RateUp,
		arg.RateUpUnit,
		arg.Burst,
		arg.ID,
	)
	return err
}
