// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: coupons.sql

package db

import (
	"context"
	"strings"
)

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (code, type, value, description, max_usage, min_order, max_discount, start_date, end_date, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, code, type, value, description, max_usage, used, min_order, max_discount, start_date, end_date, status, created_at
`

type CreateCouponParams struct {
	Code        string
	Type        string
	Value       int64
	Description string
	MaxUsage    int64
	MinOrder    int64
	MaxDiscount int64
	StartDate   string
	EndDate     string
	Status      string
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, createCoupon,
		arg.Code,
		arg.Type,
		arg.Value,
		arg.Description,
		arg.MaxUsage,
		arg.MinOrder,
		arg.MaxDiscount,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.Description,
		&i.MaxUsage,
		&i.Used,
		&i.MinOrder,
		&i.MaxDiscount,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCoupon = `-- name: DeleteCoupon :exec
DELETE FROM coupons WHERE id = ?
`

func (q *Queries) DeleteCoupon(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCoupon, id)
	return err
}

const deleteCouponsByIDs = `-- name: DeleteCouponsByIDs :execrows
DELETE FROM coupons WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteCouponsByIDs(ctx context.Context, ids []int64) (int64, error) {
	query := deleteCouponsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCoupon = `-- name: GetCoupon :one
SELECT id, code, type, value, description, max_usage, used, min_order, max_discount, start_date, end_date, status, created_at FROM coupons WHERE id = ?
`

func (q *Queries) GetCoupon(ctx context.Context, id int64) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCoupon, id)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.Description,
		&i.MaxUsage,
		&i.Used,
		&i.MinOrder,
		&i.MaxDiscount,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, type, value, description, max_usage, used, min_order, max_discount, start_date, end_date, status, created_at FROM coupons WHERE code = ?
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCouponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.Description,
		&i.MaxUsage,
		&i.Used,
		&i.MinOrder,
		&i.MaxDiscount,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const searchCoupons = `-- name: SearchCoupons :many
SELECT id, code, type, value, description, max_usage, used, min_order, max_discount, start_date, end_date, status, created_at FROM coupons WHERE code LIKE '%' || CAST(?1 AS TEXT) || '%' OR description LIKE '%' || CAST(?1 AS TEXT) || '%'
ORDER BY id DESC LIMIT ?3 OFFSET ?2
`

type SearchCouponsParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchCoupons(ctx context.Context, arg SearchCouponsParams) ([]Coupon, error) {
	rows, err := q.db.QueryContext(ctx, searchCoupons, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Type,
			&i.Value,
			&i.Description,
			&i.MaxUsage,
			&i.Used,
			&i.MinOrder,
			&i.MaxDiscount,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleCoupon = `-- name: ToggleCoupon :exec
UPDATE coupons SET status = CASE status WHEN 'active' THEN 'inactive' ELSE 'active' END WHERE id = ?
`

func (q *Queries) ToggleCoupon(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, toggleCoupon, id)
	return err
}

const updateCoupon = `-- name: UpdateCoupon :exec
UPDATE coupons SET code = ?, type = ?, value = ?, description = ?, max_usage = ?, min_order = ?, max_discount = ?,
  start_date = ?, end_date = ?, status = ? WHERE id = ?
`

type UpdateCouponParams struct {
	Code        string
	Type        string
	Value       int64
	Description string
	MaxUsage    int64
	MinOrder    int64
	MaxDiscount int64
	StartDate   string
	EndDate     string
	Status      string
	ID          int64
}

func (q *Queries) UpdateCoupon(ctx context.Context, arg UpdateCouponParams) error {
	_, err := q.db.ExecContext(ctx, updateCoupon,
		arg.Code,
		arg.Type,
		arg.Value,
		arg.Description,
		arg.MaxUsage,
		arg.MinOrder,
		arg.MaxDiscount,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.ID,
	)
	return err
}

const useCoupon = `-- name: UseCoupon :execrows
UPDATE coupons SET used = used + 1 WHERE id = ? AND (max_usage = 0 OR used < max_usage)
`

func (q *Queries) UseCoupon(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, useCoupon, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
