// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: customers_rename.sql

package db

import (
	"context"
)

const findLoginNameOwner = `-- name: FindLoginNameOwner :one
SELECT id FROM customers
WHERE id <> ?1 AND (username = ?2 OR (pppoe_username <> '' AND pppoe_username = ?2))
LIMIT 1
`

type FindLoginNameOwnerParams struct {
	Self int64
	Name string
}

// Another customer that already uses name as username or pppoe_username (RADIUS accepts either).
func (q *Queries) FindLoginNameOwner(ctx context.Context, arg FindLoginNameOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findLoginNameOwner, arg.Self, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const renameCustomer = `-- name: RenameCustomer :exec
UPDATE customers SET username = ? WHERE id = ?
`

type RenameCustomerParams struct {
	Username string
	ID       int64
}

func (q *Queries) RenameCustomer(ctx context.Context, arg RenameCustomerParams) error {
	_, err := q.db.ExecContext(ctx, renameCustomer, arg.Username, arg.ID)
	return err
}
