// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: customers.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const adjustBalance = `-- name: AdjustBalance :one
UPDATE customers SET balance = balance + ?1 WHERE id = ?2
RETURNING balance
`

type AdjustBalanceParams struct {
	Delta int64
	ID    int64
}

// delta may be negative; CHECK (balance >= 0) rejects overdraw.
func (q *Queries) AdjustBalance(ctx context.Context, arg AdjustBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adjustBalance, arg.Delta, arg.ID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (username, password_hash, fullname, address, phone, email, service_type,
                       pppoe_username, pppoe_ip, secret_enc, auto_renewal, status, created_by, billing_day, coordinates)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at, session_version, coordinates
`

type CreateCustomerParams struct {
	Username      string
	PasswordHash  string
	Fullname      string
	Address       string
	Phone         string
	Email         string
	ServiceType   string
	PppoeUsername string
	PppoeIp       string
	SecretEnc     []byte
	AutoRenewal   int64
	Status        string
	CreatedBy     sql.NullInt64
	BillingDay    sql.NullInt64
	Coordinates   string
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.Username,
		arg.PasswordHash,
		arg.Fullname,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.ServiceType,
		arg.PppoeUsername,
		arg.PppoeIp,
		arg.SecretEnc,
		arg.AutoRenewal,
		arg.Status,
		arg.CreatedBy,
		arg.BillingDay,
		arg.Coordinates,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Fullname,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Balance,
		&i.ServiceType,
		&i.PppoeUsername,
		&i.PppoeIp,
		&i.SecretEnc,
		&i.BillingDay,
		&i.AutoRenewal,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.SessionVersion,
		&i.Coordinates,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers WHERE id = ?
`

func (q *Queries) DeleteCustomer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCustomer, id)
	return err
}

const detachCustomerTransactions = `-- name: DetachCustomerTransactions :exec
UPDATE transactions SET customer_id = NULL WHERE customer_id = ?
`

// Customer delete keeps history: transactions stay with customer_id NULL (username/plan_name remain).
func (q *Queries) DetachCustomerTransactions(ctx context.Context, customerID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, detachCustomerTransactions, customerID)
	return err
}

const filterCustomers = `-- name: FilterCustomers :many
SELECT c.id, c.username, c.password_hash, c.fullname, c.address, c.phone, c.email, c.balance, c.service_type, c.pppoe_username, c.pppoe_ip, c.secret_enc, c.billing_day, c.auto_renewal, c.status, c.created_by, c.created_at, c.last_login_at, c.session_version, c.coordinates, CAST(COALESCE((SELECT group_concat(p.name, ', ') FROM subscriptions s JOIN plans p ON p.id = s.plan_id
                           WHERE s.customer_id = c.id AND s.status = 'active'), '') AS TEXT) AS packages,
       CAST(?1 AS TEXT) AS sort_key -- e.g. username_desc; anything else = newest first
FROM customers c
WHERE (c.username LIKE '%' || CAST(?2 AS TEXT) || '%' OR c.fullname LIKE '%' || CAST(?2 AS TEXT) || '%'
       OR c.phone LIKE '%' || CAST(?2 AS TEXT) || '%' OR c.pppoe_username LIKE '%' || CAST(?2 AS TEXT) || '%')
  AND (CAST(?3 AS TEXT) = '' OR c.service_type = ?3)
  AND (CAST(?4 AS TEXT) = '' OR c.status = ?4)
ORDER BY
  CASE WHEN sort_key = 'username_asc' THEN c.username END ASC,
  CASE WHEN sort_key = 'username_desc' THEN c.username END DESC,
  CASE WHEN sort_key = 'fullname_asc' THEN c.fullname END ASC,
  CASE WHEN sort_key = 'fullname_desc' THEN c.fullname END DESC,
  CASE WHEN sort_key = 'balance_asc' THEN c.balance END ASC,
  CASE WHEN sort_key = 'balance_desc' THEN c.balance END DESC,
  CASE WHEN sort_key = 'status_asc' THEN c.status END ASC,
  CASE WHEN sort_key = 'status_desc' THEN c.status END DESC,
  c.id DESC
LIMIT ?6 OFFSET ?5
`

type FilterCustomersParams struct {
	Sort        string
	Q           string
	ServiceType string
	Status      string
	PageOffset  int64
	PageLimit   int64
}

type FilterCustomersRow struct {
	ID             int64
	Username       string
	PasswordHash   string
	Fullname       string
	Address        string
	Phone          string
	Email          string
	Balance        int64
	ServiceType    string
	PppoeUsername  string
	PppoeIp        string
	SecretEnc      []byte
	BillingDay     sql.NullInt64
	AutoRenewal    int64
	Status         string
	CreatedBy      sql.NullInt64
	CreatedAt      int64
	LastLoginAt    sql.NullInt64
	SessionVersion int64
	Coordinates    string
	Packages       string
	SortKey        string
}

// Empty service_type/status = any. page_limit -1 = all rows (CSV).
func (q *Queries) FilterCustomers(ctx context.Context, arg FilterCustomersParams) ([]FilterCustomersRow, error) {
	rows, err := q.db.QueryContext(ctx, filterCustomers,
		arg.Sort,
		arg.Q,
		arg.ServiceType,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterCustomersRow
	for rows.Next() {
		var i FilterCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Fullname,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Balance,
			&i.ServiceType,
			&i.PppoeUsername,
			&i.PppoeIp,
			&i.SecretEnc,
			&i.BillingDay,
			&i.AutoRenewal,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.SessionVersion,
			&i.Coordinates,
			&i.Packages,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at, session_version, coordinates FROM customers WHERE id = ?
`

func (q *Queries) GetCustomer(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Fullname,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Balance,
		&i.ServiceType,
		&i.PppoeUsername,
		&i.PppoeIp,
		&i.SecretEnc,
		&i.BillingDay,
		&i.AutoRenewal,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.SessionVersion,
		&i.Coordinates,
	)
	return i, err
}

const getCustomerByUsername = `-- name: GetCustomerByUsername :one
SELECT id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at, session_version, coordinates FROM customers WHERE username = ?
`

func (q *Queries) GetCustomerByUsername(ctx context.Context, username string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByUsername, username)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Fullname,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Balance,
		&i.ServiceType,
		&i.PppoeUsername,
		&i.PppoeIp,
		&i.SecretEnc,
		&i.BillingDay,
		&i.AutoRenewal,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.SessionVersion,
		&i.Coordinates,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at, session_version, coordinates FROM customers ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListCustomersParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Fullname,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Balance,
			&i.ServiceType,
			&i.PppoeUsername,
			&i.PppoeIp,
			&i.SecretEnc,
			&i.BillingDay,
			&i.AutoRenewal,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.SessionVersion,
			&i.Coordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByIDs = `-- name: ListCustomersByIDs :many
SELECT id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at, session_version, coordinates FROM customers WHERE id IN (/*SLICE:ids*/?) ORDER BY id
`

func (q *Queries) ListCustomersByIDs(ctx context.Context, ids []int64) ([]Customer, error) {
	query := listCustomersByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Fullname,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Balance,
			&i.ServiceType,
			&i.PppoeUsername,
			&i.PppoeIp,
			&i.SecretEnc,
			&i.BillingDay,
			&i.AutoRenewal,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.SessionVersion,
			&i.Coordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quickSearchCustomers = `-- name: QuickSearchCustomers :many
SELECT id, username, fullname, phone, pppoe_username, status, balance FROM customers
WHERE CAST(?1 AS TEXT) = ''
   OR instr(lower(username), lower(CAST(?1 AS TEXT))) > 0
   OR instr(lower(fullname), lower(CAST(?1 AS TEXT))) > 0
   OR instr(lower(phone), lower(CAST(?1 AS TEXT))) > 0
   OR instr(lower(pppoe_username), lower(CAST(?1 AS TEXT))) > 0
ORDER BY (CAST(?1 AS TEXT) <> '' AND (lower(username) = lower(CAST(?1 AS TEXT)) OR (pppoe_username <> '' AND lower(pppoe_username) = lower(CAST(?1 AS TEXT))) OR phone = CAST(?1 AS TEXT))) DESC,
   (CAST(?1 AS TEXT) = '' AND status <> 'Active'), username
LIMIT ?2
`

type QuickSearchCustomersParams struct {
	Term  string
	Limit int64
}

type QuickSearchCustomersRow struct {
	ID            int64
	Username      string
	Fullname      string
	Phone         string
	PppoeUsername string
	Status        string
	Balance       int64
}

// Header type-ahead and customer picker. Empty term: the first customers, Active first, then username.
// Otherwise case-insensitive substring match with instr (no LIKE wildcards to escape); exact matches sort first.
func (q *Queries) QuickSearchCustomers(ctx context.Context, arg QuickSearchCustomersParams) ([]QuickSearchCustomersRow, error) {
	rows, err := q.db.QueryContext(ctx, quickSearchCustomers, arg.Term, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuickSearchCustomersRow
	for rows.Next() {
		var i QuickSearchCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Fullname,
			&i.Phone,
			&i.PppoeUsername,
			&i.Status,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomers = `-- name: SearchCustomers :many
SELECT id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at, session_version, coordinates FROM customers
WHERE username LIKE '%' || CAST(?1 AS TEXT) || '%'
   OR fullname LIKE '%' || CAST(?1 AS TEXT) || '%'
   OR phone LIKE '%' || CAST(?1 AS TEXT) || '%'
ORDER BY id DESC LIMIT ?3 OFFSET ?2
`

type SearchCustomersParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, searchCustomers, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Fullname,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Balance,
			&i.ServiceType,
			&i.PppoeUsername,
			&i.PppoeIp,
			&i.SecretEnc,
			&i.BillingDay,
			&i.AutoRenewal,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.SessionVersion,
			&i.Coordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerPassword = `-- name: SetCustomerPassword :exec
UPDATE customers SET password_hash = ?, session_version = session_version + 1 WHERE id = ?
`

type SetCustomerPasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) SetCustomerPassword(ctx context.Context, arg SetCustomerPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setCustomerPassword, arg.PasswordHash, arg.ID)
	return err
}

const setCustomerSecret = `-- name: SetCustomerSecret :exec
UPDATE customers SET secret_enc = ? WHERE id = ?
`

type SetCustomerSecretParams struct {
	SecretEnc []byte
	ID        int64
}

func (q *Queries) SetCustomerSecret(ctx context.Context, arg SetCustomerSecretParams) error {
	_, err := q.db.ExecContext(ctx, setCustomerSecret, arg.SecretEnc, arg.ID)
	return err
}

const touchCustomerLogin = `-- name: TouchCustomerLogin :exec
UPDATE customers SET last_login_at = unixepoch() WHERE id = ?
`

func (q *Queries) TouchCustomerLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchCustomerLogin, id)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers SET fullname = ?, address = ?, phone = ?, email = ?, service_type = ?,
    pppoe_username = ?, pppoe_ip = ?, secret_enc = ?, auto_renewal = ?, status = ?, billing_day = ?, coordinates = ?
WHERE id = ?
`

type UpdateCustomerParams struct {
	Fullname      string
	Address       string
	Phone         string
	Email         string
	ServiceType   string
	PppoeUsername string
	PppoeIp       string
	SecretEnc     []byte
	AutoRenewal   int64
	Status        string
	BillingDay    sql.NullInt64
	Coordinates   string
	ID            int64
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomer,
		arg.Fullname,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.ServiceType,
		arg.PppoeUsername,
		arg.PppoeIp,
		arg.SecretEnc,
		arg.AutoRenewal,
		arg.Status,
		arg.BillingDay,
		arg.Coordinates,
		arg.ID,
	)
	return err
}
