// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: customers.sql

package db

import (
	"context"
	"database/sql"
)

const adjustBalance = `-- name: AdjustBalance :one
UPDATE customers SET balance = balance + ?1 WHERE id = ?2
RETURNING balance
`

type AdjustBalanceParams struct {
	Delta int64
	ID    int64
}

// delta may be negative; CHECK (balance >= 0) rejects overdraw.
func (q *Queries) AdjustBalance(ctx context.Context, arg AdjustBalanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adjustBalance, arg.Delta, arg.ID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (username, password_hash, fullname, address, phone, email, service_type,
                       pppoe_username, pppoe_ip, secret_enc, auto_renewal, status, created_by, billing_day)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at
`

type CreateCustomerParams struct {
	Username      string
	PasswordHash  string
	Fullname      string
	Address       string
	Phone         string
	Email         string
	ServiceType   string
	PppoeUsername string
	PppoeIp       string
	SecretEnc     []byte
	AutoRenewal   int64
	Status        string
	CreatedBy     sql.NullInt64
	BillingDay    sql.NullInt64
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.Username,
		arg.PasswordHash,
		arg.Fullname,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.ServiceType,
		arg.PppoeUsername,
		arg.PppoeIp,
		arg.SecretEnc,
		arg.AutoRenewal,
		arg.Status,
		arg.CreatedBy,
		arg.BillingDay,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Fullname,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Balance,
		&i.ServiceType,
		&i.PppoeUsername,
		&i.PppoeIp,
		&i.SecretEnc,
		&i.BillingDay,
		&i.AutoRenewal,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers WHERE id = ?
`

func (q *Queries) DeleteCustomer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCustomer, id)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at FROM customers WHERE id = ?
`

func (q *Queries) GetCustomer(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Fullname,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Balance,
		&i.ServiceType,
		&i.PppoeUsername,
		&i.PppoeIp,
		&i.SecretEnc,
		&i.BillingDay,
		&i.AutoRenewal,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getCustomerByUsername = `-- name: GetCustomerByUsername :one
SELECT id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at FROM customers WHERE username = ?
`

func (q *Queries) GetCustomerByUsername(ctx context.Context, username string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByUsername, username)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Fullname,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Balance,
		&i.ServiceType,
		&i.PppoeUsername,
		&i.PppoeIp,
		&i.SecretEnc,
		&i.BillingDay,
		&i.AutoRenewal,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at FROM customers ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListCustomersParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Fullname,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Balance,
			&i.ServiceType,
			&i.PppoeUsername,
			&i.PppoeIp,
			&i.SecretEnc,
			&i.BillingDay,
			&i.AutoRenewal,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomers = `-- name: SearchCustomers :many
SELECT id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at FROM customers
WHERE username LIKE '%' || CAST(?1 AS TEXT) || '%'
   OR fullname LIKE '%' || CAST(?1 AS TEXT) || '%'
   OR phone LIKE '%' || CAST(?1 AS TEXT) || '%'
ORDER BY id DESC LIMIT ?3 OFFSET ?2
`

type SearchCustomersParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, searchCustomers, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Fullname,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Balance,
			&i.ServiceType,
			&i.PppoeUsername,
			&i.PppoeIp,
			&i.SecretEnc,
			&i.BillingDay,
			&i.AutoRenewal,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerPassword = `-- name: SetCustomerPassword :exec
UPDATE customers SET password_hash = ? WHERE id = ?
`

type SetCustomerPasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) SetCustomerPassword(ctx context.Context, arg SetCustomerPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setCustomerPassword, arg.PasswordHash, arg.ID)
	return err
}

const touchCustomerLogin = `-- name: TouchCustomerLogin :exec
UPDATE customers SET last_login_at = unixepoch() WHERE id = ?
`

func (q *Queries) TouchCustomerLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchCustomerLogin, id)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers SET fullname = ?, address = ?, phone = ?, email = ?, service_type = ?,
    pppoe_username = ?, pppoe_ip = ?, secret_enc = ?, auto_renewal = ?, status = ?, billing_day = ?
WHERE id = ?
`

type UpdateCustomerParams struct {
	Fullname      string
	Address       string
	Phone         string
	Email         string
	ServiceType   string
	PppoeUsername string
	PppoeIp       string
	SecretEnc     []byte
	AutoRenewal   int64
	Status        string
	BillingDay    sql.NullInt64
	ID            int64
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomer,
		arg.Fullname,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.ServiceType,
		arg.PppoeUsername,
		arg.PppoeIp,
		arg.SecretEnc,
		arg.AutoRenewal,
		arg.Status,
		arg.BillingDay,
		arg.ID,
	)
	return err
}
