// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: dashboard.sql

package db

import (
	"context"
)

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*) FROM customers
`

func (q *Queries) CountCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomersBetween = `-- name: CountCustomersBetween :one
SELECT COUNT(*) FROM customers WHERE created_at >= ? AND created_at < ?
`

type CountCustomersBetweenParams struct {
	CreatedAt   int64
	CreatedAt_2 int64
}

func (q *Queries) CountCustomersBetween(ctx context.Context, arg CountCustomersBetweenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCustomersBetween, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubscriptionsByStatus = `-- name: CountSubscriptionsByStatus :one
SELECT COUNT(*) FROM subscriptions WHERE status = ?
`

func (q *Queries) CountSubscriptionsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscriptionsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}
