// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: fields_pages.sql

package db

import (
	"context"
)

const createCustomField = `-- name: CreateCustomField :one
INSERT INTO custom_fields (name, type, options, required, sort_order)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, type, options, required, sort_order
`

type CreateCustomFieldParams struct {
	Name      string
	Type      string
	Options   string
	Required  int64
	SortOrder int64
}

func (q *Queries) CreateCustomField(ctx context.Context, arg CreateCustomFieldParams) (CustomField, error) {
	row := q.db.QueryRowContext(ctx, createCustomField,
		arg.Name,
		arg.Type,
		arg.Options,
		arg.Required,
		arg.SortOrder,
	)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Options,
		&i.Required,
		&i.SortOrder,
	)
	return i, err
}

const deleteCustomField = `-- name: DeleteCustomField :exec
DELETE FROM custom_fields WHERE id = ?
`

func (q *Queries) DeleteCustomField(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCustomField, id)
	return err
}

const getCustomField = `-- name: GetCustomField :one
SELECT id, name, type, options, required, sort_order FROM custom_fields WHERE id = ?
`

func (q *Queries) GetCustomField(ctx context.Context, id int64) (CustomField, error) {
	row := q.db.QueryRowContext(ctx, getCustomField, id)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Options,
		&i.Required,
		&i.SortOrder,
	)
	return i, err
}

const getPage = `-- name: GetPage :one
SELECT slug, title, body FROM pages WHERE slug = ?
`

func (q *Queries) GetPage(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPage, slug)
	var i Page
	err := row.Scan(&i.Slug, &i.Title, &i.Body)
	return i, err
}

const listCustomFields = `-- name: ListCustomFields :many
SELECT id, name, type, options, required, sort_order FROM custom_fields ORDER BY sort_order, id
`

func (q *Queries) ListCustomFields(ctx context.Context) ([]CustomField, error) {
	rows, err := q.db.QueryContext(ctx, listCustomFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomField
	for rows.Next() {
		var i CustomField
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Options,
			&i.Required,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerFieldValues = `-- name: ListCustomerFieldValues :many
SELECT customer_id, field_id, value FROM customer_field_values WHERE customer_id = ?
`

func (q *Queries) ListCustomerFieldValues(ctx context.Context, customerID int64) ([]CustomerFieldValue, error) {
	rows, err := q.db.QueryContext(ctx, listCustomerFieldValues, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerFieldValue
	for rows.Next() {
		var i CustomerFieldValue
		if err := rows.Scan(&i.CustomerID, &i.FieldID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomField = `-- name: UpdateCustomField :exec
UPDATE custom_fields SET name = ?, type = ?, options = ?, required = ?, sort_order = ?
WHERE id = ?
`

type UpdateCustomFieldParams struct {
	Name      string
	Type      string
	Options   string
	Required  int64
	SortOrder int64
	ID        int64
}

func (q *Queries) UpdateCustomField(ctx context.Context, arg UpdateCustomFieldParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomField,
		arg.Name,
		arg.Type,
		arg.Options,
		arg.Required,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const updatePageBody = `-- name: UpdatePageBody :exec
UPDATE pages SET body = ? WHERE slug = ?
`

type UpdatePageBodyParams struct {
	Body string
	Slug string
}

func (q *Queries) UpdatePageBody(ctx context.Context, arg UpdatePageBodyParams) error {
	_, err := q.db.ExecContext(ctx, updatePageBody, arg.Body, arg.Slug)
	return err
}

const upsertCustomerFieldValue = `-- name: UpsertCustomerFieldValue :exec
INSERT INTO customer_field_values (customer_id, field_id, value) VALUES (?, ?, ?)
ON CONFLICT (customer_id, field_id) DO UPDATE SET value = excluded.value
`

type UpsertCustomerFieldValueParams struct {
	CustomerID int64
	FieldID    int64
	Value      string
}

func (q *Queries) UpsertCustomerFieldValue(ctx context.Context, arg UpsertCustomerFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertCustomerFieldValue, arg.CustomerID, arg.FieldID, arg.Value)
	return err
}
