// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: messages.sql

package db

import (
	"context"
)

const countUnreadInbox = `-- name: CountUnreadInbox :one
SELECT COUNT(*) FROM customers_inbox WHERE customer_id = ? AND read_at IS NULL
`

func (q *Queries) CountUnreadInbox(ctx context.Context, customerID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadInbox, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInboxMessage = `-- name: CreateInboxMessage :exec
INSERT INTO customers_inbox (customer_id, from_name, subject, body) VALUES (?, ?, ?, ?)
`

type CreateInboxMessageParams struct {
	CustomerID int64
	FromName   string
	Subject    string
	Body       string
}

func (q *Queries) CreateInboxMessage(ctx context.Context, arg CreateInboxMessageParams) error {
	_, err := q.db.ExecContext(ctx, createInboxMessage,
		arg.CustomerID,
		arg.FromName,
		arg.Subject,
		arg.Body,
	)
	return err
}

const createMessageLog = `-- name: CreateMessageLog :exec
INSERT INTO message_logs (channel, recipient, subject, body, status, error) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMessageLogParams struct {
	Channel   string
	Recipient string
	Subject   string
	Body      string
	Status    string
	Error     string
}

func (q *Queries) CreateMessageLog(ctx context.Context, arg CreateMessageLogParams) error {
	_, err := q.db.ExecContext(ctx, createMessageLog,
		arg.Channel,
		arg.Recipient,
		arg.Subject,
		arg.Body,
		arg.Status,
		arg.Error,
	)
	return err
}

const getInboxMessage = `-- name: GetInboxMessage :one
SELECT id, customer_id, from_name, subject, body, read_at, created_at FROM customers_inbox WHERE id = ? AND customer_id = ?
`

type GetInboxMessageParams struct {
	ID         int64
	CustomerID int64
}

func (q *Queries) GetInboxMessage(ctx context.Context, arg GetInboxMessageParams) (CustomersInbox, error) {
	row := q.db.QueryRowContext(ctx, getInboxMessage, arg.ID, arg.CustomerID)
	var i CustomersInbox
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FromName,
		&i.Subject,
		&i.Body,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInboxByCustomer = `-- name: ListInboxByCustomer :many
SELECT id, customer_id, from_name, subject, body, read_at, created_at FROM customers_inbox WHERE customer_id = ? ORDER BY id DESC LIMIT ?
`

type ListInboxByCustomerParams struct {
	CustomerID int64
	Limit      int64
}

func (q *Queries) ListInboxByCustomer(ctx context.Context, arg ListInboxByCustomerParams) ([]CustomersInbox, error) {
	rows, err := q.db.QueryContext(ctx, listInboxByCustomer, arg.CustomerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomersInbox
	for rows.Next() {
		var i CustomersInbox
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.FromName,
			&i.Subject,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageRecipients = `-- name: ListMessageRecipients :many
SELECT c.id, c.username, c.password_hash, c.fullname, c.address, c.phone, c.email, c.balance, c.service_type, c.pppoe_username, c.pppoe_ip, c.secret_enc, c.billing_day, c.auto_renewal, c.status, c.created_by, c.created_at, c.last_login_at, c.coordinates FROM customers c
WHERE (CAST(?1 AS TEXT) = '' OR c.service_type = ?1)
  AND ((CAST(?2 AS INTEGER) = 0 AND CAST(?3 AS TEXT) = '') OR EXISTS (
        SELECT 1 FROM subscriptions s
        WHERE s.customer_id = c.id
          AND (CAST(?2 AS INTEGER) = 0 OR s.router_id = CAST(?2 AS INTEGER))
          AND (CAST(?3 AS TEXT) = '' OR s.status = ?3)))
ORDER BY c.id
`

type ListMessageRecipientsParams struct {
	ServiceType string
	RouterID    int64
	SubStatus   string
}

// Empty service_type/sub_status and router_id 0 = any. Filters on router/status match a subscription.
func (q *Queries) ListMessageRecipients(ctx context.Context, arg ListMessageRecipientsParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listMessageRecipients, arg.ServiceType, arg.RouterID, arg.SubStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Fullname,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Balance,
			&i.ServiceType,
			&i.PppoeUsername,
			&i.PppoeIp,
			&i.SecretEnc,
			&i.BillingDay,
			&i.AutoRenewal,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.Coordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxRead = `-- name: MarkInboxRead :exec
UPDATE customers_inbox SET read_at = unixepoch() WHERE id = ? AND customer_id = ? AND read_at IS NULL
`

type MarkInboxReadParams struct {
	ID         int64
	CustomerID int64
}

func (q *Queries) MarkInboxRead(ctx context.Context, arg MarkInboxReadParams) error {
	_, err := q.db.ExecContext(ctx, markInboxRead, arg.ID, arg.CustomerID)
	return err
}

const searchMessageLogs = `-- name: SearchMessageLogs :many
SELECT id, channel, recipient, subject, body, status, error, created_at FROM message_logs
WHERE (recipient LIKE '%' || CAST(?1 AS TEXT) || '%' OR subject LIKE '%' || CAST(?1 AS TEXT) || '%'
       OR body LIKE '%' || CAST(?1 AS TEXT) || '%' OR channel LIKE '%' || CAST(?1 AS TEXT) || '%')
  AND (CAST(?2 AS INTEGER) = 0 OR created_at >= ?2)
  AND (CAST(?3 AS INTEGER) = 0 OR created_at < ?3)
ORDER BY id DESC LIMIT ?5 OFFSET ?4
`

type SearchMessageLogsParams struct {
	Q          string
	FromTs     int64
	ToTs       int64
	PageOffset int64
	PageLimit  int64
}

// created_at range: from_ts/to_ts 0 = open. page_limit -1 = all (CSV).
func (q *Queries) SearchMessageLogs(ctx context.Context, arg SearchMessageLogsParams) ([]MessageLog, error) {
	rows, err := q.db.QueryContext(ctx, searchMessageLogs,
		arg.Q,
		arg.FromTs,
		arg.ToTs,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageLog
	for rows.Next() {
		var i MessageLog
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.Recipient,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
