// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Admin struct {
	ID           int64
	Username     string
	Fullname     string
	PasswordHash string
	Role         string
	Status       string
	LastLoginAt  sql.NullInt64
	CreatedAt    int64
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Setting struct {
	Key   string
	Value string
}
