// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type ActivityLog struct {
	ID          int64
	ActorType   string
	ActorID     int64
	Action      string
	Description string
	Ip          string
	CreatedAt   int64
}

type Admin struct {
	ID             int64
	Username       string
	Fullname       string
	PasswordHash   string
	LegacySha1     string
	Role           string
	Status         string
	Email          string
	Phone          string
	City           string
	RootID         sql.NullInt64
	SessionVersion int64
	LastLoginAt    sql.NullInt64
	CreatedAt      int64
	TotpSecretEnc  string
	TotpEnabled    int64
}

type AdminRecoveryCode struct {
	ID       int64
	AdminID  int64
	CodeHash string
	UsedAt   sql.NullInt64
}

type Bandwidth struct {
	ID           int64
	Name         string
	RateDown     int64
	RateDownUnit string
	RateUp       int64
	RateUpUnit   string
	Burst        string
}

type Coupon struct {
	ID          int64
	Code        string
	Type        string
	Value       int64
	Description string
	MaxUsage    int64
	Used        int64
	MinOrder    int64
	MaxDiscount int64
	StartDate   string
	EndDate     string
	Status      string
	CreatedAt   int64
}

type CustomField struct {
	ID        int64
	Name      string
	Type      string
	Options   string
	Required  int64
	SortOrder int64
}

type Customer struct {
	ID             int64
	Username       string
	PasswordHash   string
	Fullname       string
	Address        string
	Phone          string
	Email          string
	Balance        int64
	ServiceType    string
	PppoeUsername  string
	PppoeIp        string
	SecretEnc      []byte
	BillingDay     sql.NullInt64
	AutoRenewal    int64
	Status         string
	CreatedBy      sql.NullInt64
	CreatedAt      int64
	LastLoginAt    sql.NullInt64
	SessionVersion int64
	Coordinates    string
}

type CustomerFieldValue struct {
	CustomerID int64
	FieldID    int64
	Value      string
}

type CustomersInbox struct {
	ID         int64
	CustomerID int64
	FromName   string
	Subject    string
	Body       string
	ReadAt     sql.NullInt64
	CreatedAt  int64
}

type MessageLog struct {
	ID        int64
	Channel   string
	Recipient string
	Subject   string
	Body      string
	Status    string
	Error     string
	CreatedAt int64
}

type Na struct {
	ID                 int64
	Name               string
	Ip                 string
	SecretEnc          []byte
	Description        string
	RequireMessageAuth int64
}

type Odp struct {
	ID          int64
	Name        string
	Coordinates string
	Address     string
	PortAmount  int64
	Attenuation string
	Coverage    int64
	Description string
	RouterID    sql.NullInt64
}

type Page struct {
	Slug  string
	Title string
	Body  string
}

type PaymentRequest struct {
	ID         int64
	Ref        string
	Gateway    string
	GatewayRef string
	CustomerID sql.NullInt64
	Username   string
	PlanID     int64
	Amount     int64
	Coupon     string
	Channel    string
	PayUrl     string
	Status     string
	CreatedAt  int64
	PaidAt     sql.NullInt64
	ExpiresAt  int64
}

type Plan struct {
	ID            int64
	Name          string
	Type          string
	Billing       string
	Price         int64
	Validity      int64
	ValidityUnit  string
	Limited       int64
	LimitType     sql.NullString
	TimeLimit     sql.NullInt64
	TimeUnit      sql.NullString
	DataLimit     sql.NullInt64
	DataUnit      sql.NullString
	SharedUsers   sql.NullInt64
	BandwidthID   sql.NullInt64
	RouterID      sql.NullInt64
	PoolID        sql.NullInt64
	ExpiredPlanID sql.NullInt64
	BillingDay    sql.NullInt64
	OnLogin       string
	OnLogout      string
	Device        string
	Enabled       int64
}

type Pool struct {
	ID       int64
	Name     string
	LocalIp  string
	RangeIp  string
	RouterID int64
}

type RadiusSession struct {
	ID            int64
	SessionID     string
	Username      string
	NasIp         string
	NasIpAttr     string
	NasIdentifier string
	FramedIp      string
	Mac           string
	StartedAt     int64
	UpdatedAt     int64
	StoppedAt     sql.NullInt64
	InputOctets   int64
	OutputOctets  int64
}

type Router struct {
	ID          int64
	Name        string
	Host        string
	Port        int64
	Username    string
	PasswordEnc []byte
	Description string
	Enabled     int64
	Coordinates string
	Coverage    int64
	LastSeenAt  sql.NullInt64
	Online      sql.NullInt64
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Setting struct {
	Key   string
	Value string
}

type Subscription struct {
	ID                int64
	CustomerID        int64
	PlanID            int64
	RouterID          sql.NullInt64
	Type              string
	StartedAt         int64
	ExpiresAt         int64
	Status            string
	Method            string
	AdminID           sql.NullInt64
	PendingStart      int64
	ExpiredNotifiedAt sql.NullInt64
}

type Transaction struct {
	ID          int64
	Invoice     string
	CustomerID  sql.NullInt64
	PlanID      sql.NullInt64
	Username    string
	PlanName    string
	RouterName  string
	Type        string
	Price       int64
	Method      string
	Note        string
	AdminID     sql.NullInt64
	CreatedAt   int64
	PeriodStart int64
	PeriodEnd   int64
}

type Voucher struct {
	ID          int64
	Code        string
	PlanID      int64
	Status      string
	UsedBy      sql.NullInt64
	UsedAt      sql.NullInt64
	GeneratedBy sql.NullInt64
	CreatedAt   int64
}
