// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type ActivityLog struct {
	ID          int64
	ActorType   string
	ActorID     int64
	Action      string
	Description string
	Ip          string
	CreatedAt   int64
}

type Admin struct {
	ID             int64
	Username       string
	Fullname       string
	PasswordHash   string
	Role           string
	Status         string
	Email          string
	Phone          string
	City           string
	RootID         sql.NullInt64
	SessionVersion int64
	LastLoginAt    sql.NullInt64
	CreatedAt      int64
}

type Bandwidth struct {
	ID           int64
	Name         string
	RateDown     int64
	RateDownUnit string
	RateUp       int64
	RateUpUnit   string
	Burst        string
}

type Customer struct {
	ID            int64
	Username      string
	PasswordHash  string
	Fullname      string
	Address       string
	Phone         string
	Email         string
	Balance       int64
	ServiceType   string
	PppoeUsername string
	PppoeIp       string
	SecretEnc     []byte
	BillingDay    sql.NullInt64
	AutoRenewal   int64
	Status        string
	CreatedBy     sql.NullInt64
	CreatedAt     int64
	LastLoginAt   sql.NullInt64
}

type Na struct {
	ID          int64
	Name        string
	Ip          string
	SecretEnc   []byte
	Description string
}

type Plan struct {
	ID            int64
	Name          string
	Type          string
	Billing       string
	Price         int64
	Validity      int64
	ValidityUnit  string
	Limited       int64
	LimitType     sql.NullString
	TimeLimit     sql.NullInt64
	TimeUnit      sql.NullString
	DataLimit     sql.NullInt64
	DataUnit      sql.NullString
	SharedUsers   sql.NullInt64
	BandwidthID   sql.NullInt64
	RouterID      sql.NullInt64
	PoolID        sql.NullInt64
	ExpiredPlanID sql.NullInt64
	BillingDay    sql.NullInt64
	OnLogin       string
	OnLogout      string
	Device        string
	Enabled       int64
}

type Pool struct {
	ID       int64
	Name     string
	LocalIp  string
	RangeIp  string
	RouterID int64
}

type RadiusSession struct {
	ID           int64
	SessionID    string
	Username     string
	NasIp        string
	FramedIp     string
	Mac          string
	StartedAt    int64
	UpdatedAt    int64
	StoppedAt    sql.NullInt64
	InputOctets  int64
	OutputOctets int64
}

type Router struct {
	ID          int64
	Name        string
	Host        string
	Port        int64
	Username    string
	PasswordEnc []byte
	Description string
	Enabled     int64
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Setting struct {
	Key   string
	Value string
}

type Subscription struct {
	ID         int64
	CustomerID int64
	PlanID     int64
	RouterID   int64
	Type       string
	StartedAt  int64
	ExpiresAt  int64
	Status     string
	Method     string
	AdminID    sql.NullInt64
}

type Transaction struct {
	ID          int64
	Invoice     string
	CustomerID  int64
	PlanID      sql.NullInt64
	Username    string
	PlanName    string
	RouterName  string
	Type        string
	Price       int64
	Method      string
	Note        string
	AdminID     sql.NullInt64
	CreatedAt   int64
	PeriodStart int64
	PeriodEnd   int64
}

type Voucher struct {
	ID          int64
	Code        string
	PlanID      int64
	Status      string
	UsedBy      sql.NullInt64
	UsedAt      sql.NullInt64
	GeneratedBy sql.NullInt64
	CreatedAt   int64
}
