// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: network.sql

package db

import (
	"context"
)

const listAllRouters = `-- name: ListAllRouters :many
SELECT id, name, host, port, username, password_enc, description, enabled, coordinates, coverage, last_seen_at, online FROM routers ORDER BY name
`

func (q *Queries) ListAllRouters(ctx context.Context) ([]Router, error) {
	rows, err := q.db.QueryContext(ctx, listAllRouters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Router
	for rows.Next() {
		var i Router
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.PasswordEnc,
			&i.Description,
			&i.Enabled,
			&i.Coordinates,
			&i.Coverage,
			&i.LastSeenAt,
			&i.Online,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNASPacketStats = `-- name: ListNASPacketStats :many
SELECT nas_ip, CAST(MAX(updated_at) AS INTEGER) AS last_seen,
       CAST(COUNT(CASE WHEN stopped_at IS NULL THEN 1 END) AS INTEGER) AS active
FROM radius_sessions GROUP BY nas_ip
`

type ListNASPacketStatsRow struct {
	NasIp    string
	LastSeen int64
	Active   int64
}

// Per NAS packet source IP: newest packet seen and sessions still open.
func (q *Queries) ListNASPacketStats(ctx context.Context) ([]ListNASPacketStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNASPacketStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNASPacketStatsRow
	for rows.Next() {
		var i ListNASPacketStatsRow
		if err := rows.Scan(&i.NasIp, &i.LastSeen, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
