// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: odp.sql

package db

import (
	"context"
	"database/sql"
)

const createODP = `-- name: CreateODP :one
INSERT INTO odps (name, coordinates, address, port_amount, attenuation, coverage, description, router_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, coordinates, address, port_amount, attenuation, coverage, description, router_id
`

type CreateODPParams struct {
	Name        string
	Coordinates string
	Address     string
	PortAmount  int64
	Attenuation string
	Coverage    int64
	Description string
	RouterID    sql.NullInt64
}

func (q *Queries) CreateODP(ctx context.Context, arg CreateODPParams) (Odp, error) {
	row := q.db.QueryRowContext(ctx, createODP,
		arg.Name,
		arg.Coordinates,
		arg.Address,
		arg.PortAmount,
		arg.Attenuation,
		arg.Coverage,
		arg.Description,
		arg.RouterID,
	)
	var i Odp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Coordinates,
		&i.Address,
		&i.PortAmount,
		&i.Attenuation,
		&i.Coverage,
		&i.Description,
		&i.RouterID,
	)
	return i, err
}

const deleteODP = `-- name: DeleteODP :exec
DELETE FROM odps WHERE id = ?
`

func (q *Queries) DeleteODP(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteODP, id)
	return err
}

const getODP = `-- name: GetODP :one
SELECT id, name, coordinates, address, port_amount, attenuation, coverage, description, router_id FROM odps WHERE id = ?
`

func (q *Queries) GetODP(ctx context.Context, id int64) (Odp, error) {
	row := q.db.QueryRowContext(ctx, getODP, id)
	var i Odp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Coordinates,
		&i.Address,
		&i.PortAmount,
		&i.Attenuation,
		&i.Coverage,
		&i.Description,
		&i.RouterID,
	)
	return i, err
}

const listCustomerMarkers = `-- name: ListCustomerMarkers :many
SELECT c.id, c.fullname, c.status, c.coordinates, CAST(COALESCE(MAX(p.name), '') AS TEXT) AS plan_name
FROM customers c
LEFT JOIN subscriptions s ON s.customer_id = c.id AND s.status = 'active'
LEFT JOIN plans p ON p.id = s.plan_id
WHERE c.coordinates != ''
GROUP BY c.id
ORDER BY c.id
`

type ListCustomerMarkersRow struct {
	ID          int64
	Fullname    string
	Status      string
	Coordinates string
	PlanName    string
}

func (q *Queries) ListCustomerMarkers(ctx context.Context) ([]ListCustomerMarkersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCustomerMarkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerMarkersRow
	for rows.Next() {
		var i ListCustomerMarkersRow
		if err := rows.Scan(
			&i.ID,
			&i.Fullname,
			&i.Status,
			&i.Coordinates,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listODPMarkers = `-- name: ListODPMarkers :many
SELECT id, name, coordinates, address, port_amount, attenuation, coverage, description, router_id FROM odps WHERE coordinates != '' ORDER BY name
`

func (q *Queries) ListODPMarkers(ctx context.Context) ([]Odp, error) {
	rows, err := q.db.QueryContext(ctx, listODPMarkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Odp
	for rows.Next() {
		var i Odp
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Coordinates,
			&i.Address,
			&i.PortAmount,
			&i.Attenuation,
			&i.Coverage,
			&i.Description,
			&i.RouterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouterMarkers = `-- name: ListRouterMarkers :many
SELECT id, name, host, description, coverage, enabled, coordinates FROM routers WHERE coordinates != '' ORDER BY name
`

type ListRouterMarkersRow struct {
	ID          int64
	Name        string
	Host        string
	Description string
	Coverage    int64
	Enabled     int64
	Coordinates string
}

func (q *Queries) ListRouterMarkers(ctx context.Context) ([]ListRouterMarkersRow, error) {
	rows, err := q.db.QueryContext(ctx, listRouterMarkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouterMarkersRow
	for rows.Next() {
		var i ListRouterMarkersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Description,
			&i.Coverage,
			&i.Enabled,
			&i.Coordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchODPs = `-- name: SearchODPs :many
SELECT id, name, coordinates, address, port_amount, attenuation, coverage, description, router_id FROM odps WHERE name LIKE '%' || CAST(?1 AS TEXT) || '%' ORDER BY name LIMIT ?3 OFFSET ?2
`

type SearchODPsParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchODPs(ctx context.Context, arg SearchODPsParams) ([]Odp, error) {
	rows, err := q.db.QueryContext(ctx, searchODPs, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Odp
	for rows.Next() {
		var i Odp
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Coordinates,
			&i.Address,
			&i.PortAmount,
			&i.Attenuation,
			&i.Coverage,
			&i.Description,
			&i.RouterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateODP = `-- name: UpdateODP :exec
UPDATE odps SET name = ?, coordinates = ?, address = ?, port_amount = ?, attenuation = ?, coverage = ?, description = ?, router_id = ?
WHERE id = ?
`

type UpdateODPParams struct {
	Name        string
	Coordinates string
	Address     string
	PortAmount  int64
	Attenuation string
	Coverage    int64
	Description string
	RouterID    sql.NullInt64
	ID          int64
}

func (q *Queries) UpdateODP(ctx context.Context, arg UpdateODPParams) error {
	_, err := q.db.ExecContext(ctx, updateODP,
		arg.Name,
		arg.Coordinates,
		arg.Address,
		arg.PortAmount,
		arg.Attenuation,
		arg.Coverage,
		arg.Description,
		arg.RouterID,
		arg.ID,
	)
	return err
}
