// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: payments.sql

package db

import (
	"context"
	"database/sql"
)

const claimPaymentPaid = `-- name: ClaimPaymentPaid :execrows
UPDATE payment_requests SET status = 'paid', paid_at = unixepoch() WHERE ref = ? AND status IN ('pending', 'expired', 'failed')
`

// The idempotent claim: 0 rows = already handled.
func (q *Queries) ClaimPaymentPaid(ctx context.Context, ref string) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimPaymentPaid, ref)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closePaymentRequest = `-- name: ClosePaymentRequest :execrows
UPDATE payment_requests SET status = ? WHERE ref = ? AND status = 'pending'
`

type ClosePaymentRequestParams struct {
	Status string
	Ref    string
}

func (q *Queries) ClosePaymentRequest(ctx context.Context, arg ClosePaymentRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closePaymentRequest, arg.Status, arg.Ref)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createPaymentRequest = `-- name: CreatePaymentRequest :one
INSERT INTO payment_requests (ref, gateway, customer_id, plan_id, amount, coupon, channel, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, ref, gateway, gateway_ref, customer_id, plan_id, amount, coupon, channel, pay_url, status, created_at, paid_at, expires_at
`

type CreatePaymentRequestParams struct {
	Ref        string
	Gateway    string
	CustomerID int64
	PlanID     int64
	Amount     int64
	Coupon     string
	Channel    string
	ExpiresAt  int64
}

func (q *Queries) CreatePaymentRequest(ctx context.Context, arg CreatePaymentRequestParams) (PaymentRequest, error) {
	row := q.db.QueryRowContext(ctx, createPaymentRequest,
		arg.Ref,
		arg.Gateway,
		arg.CustomerID,
		arg.PlanID,
		arg.Amount,
		arg.Coupon,
		arg.Channel,
		arg.ExpiresAt,
	)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.Ref,
		&i.Gateway,
		&i.GatewayRef,
		&i.CustomerID,
		&i.PlanID,
		&i.Amount,
		&i.Coupon,
		&i.Channel,
		&i.PayUrl,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ExpiresAt,
	)
	return i, err
}

const expirePaymentRequests = `-- name: ExpirePaymentRequests :execrows
UPDATE payment_requests SET status = 'expired' WHERE status = 'pending' AND expires_at < ?
`

func (q *Queries) ExpirePaymentRequests(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, expirePaymentRequests, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPaymentAudit = `-- name: GetPaymentAudit :one
SELECT p.id, p.ref, p.gateway, p.gateway_ref, p.customer_id, p.plan_id, p.amount, p.coupon, p.channel, p.pay_url, p.status, p.created_at, p.paid_at, p.expires_at, c.username, CAST(COALESCE(pl.name, 'Custom Balance') AS TEXT) AS plan_name FROM payment_requests p
JOIN customers c ON c.id = p.customer_id LEFT JOIN plans pl ON pl.id = p.plan_id WHERE p.id = ?
`

type GetPaymentAuditRow struct {
	ID         int64
	Ref        string
	Gateway    string
	GatewayRef string
	CustomerID int64
	PlanID     int64
	Amount     int64
	Coupon     string
	Channel    string
	PayUrl     string
	Status     string
	CreatedAt  int64
	PaidAt     sql.NullInt64
	ExpiresAt  int64
	Username   string
	PlanName   string
}

func (q *Queries) GetPaymentAudit(ctx context.Context, id int64) (GetPaymentAuditRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentAudit, id)
	var i GetPaymentAuditRow
	err := row.Scan(
		&i.ID,
		&i.Ref,
		&i.Gateway,
		&i.GatewayRef,
		&i.CustomerID,
		&i.PlanID,
		&i.Amount,
		&i.Coupon,
		&i.Channel,
		&i.PayUrl,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ExpiresAt,
		&i.Username,
		&i.PlanName,
	)
	return i, err
}

const getPaymentRequest = `-- name: GetPaymentRequest :one
SELECT id, ref, gateway, gateway_ref, customer_id, plan_id, amount, coupon, channel, pay_url, status, created_at, paid_at, expires_at FROM payment_requests WHERE id = ?
`

func (q *Queries) GetPaymentRequest(ctx context.Context, id int64) (PaymentRequest, error) {
	row := q.db.QueryRowContext(ctx, getPaymentRequest, id)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.Ref,
		&i.Gateway,
		&i.GatewayRef,
		&i.CustomerID,
		&i.PlanID,
		&i.Amount,
		&i.Coupon,
		&i.Channel,
		&i.PayUrl,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPaymentRequestByRef = `-- name: GetPaymentRequestByRef :one
SELECT id, ref, gateway, gateway_ref, customer_id, plan_id, amount, coupon, channel, pay_url, status, created_at, paid_at, expires_at FROM payment_requests WHERE ref = ?
`

func (q *Queries) GetPaymentRequestByRef(ctx context.Context, ref string) (PaymentRequest, error) {
	row := q.db.QueryRowContext(ctx, getPaymentRequestByRef, ref)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.Ref,
		&i.Gateway,
		&i.GatewayRef,
		&i.CustomerID,
		&i.PlanID,
		&i.Amount,
		&i.Coupon,
		&i.Channel,
		&i.PayUrl,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ExpiresAt,
	)
	return i, err
}

const searchPaymentRequests = `-- name: SearchPaymentRequests :many
SELECT p.id, p.ref, p.gateway, p.gateway_ref, p.customer_id, p.plan_id, p.amount, p.coupon, p.channel, p.pay_url, p.status, p.created_at, p.paid_at, p.expires_at, c.username, CAST(COALESCE(pl.name, 'Custom Balance') AS TEXT) AS plan_name FROM payment_requests p
JOIN customers c ON c.id = p.customer_id LEFT JOIN plans pl ON pl.id = p.plan_id
WHERE (CAST(?1 AS TEXT) = '' OR p.ref LIKE '%' || CAST(?1 AS TEXT) || '%' OR p.gateway_ref LIKE '%' || CAST(?1 AS TEXT) || '%'
       OR c.username LIKE '%' || CAST(?1 AS TEXT) || '%' OR COALESCE(pl.name, 'Custom Balance') LIKE '%' || CAST(?1 AS TEXT) || '%')
  AND (CAST(?2 AS TEXT) = '' OR p.status = ?2)
  AND (CAST(?3 AS INTEGER) = 0 OR p.created_at >= ?3)
  AND (CAST(?4 AS INTEGER) = 0 OR p.created_at < ?4)
ORDER BY p.id DESC LIMIT ?6 OFFSET ?5
`

type SearchPaymentRequestsParams struct {
	Q          string
	Status     string
	FromTs     int64
	ToTs       int64
	PageOffset int64
	PageLimit  int64
}

type SearchPaymentRequestsRow struct {
	ID         int64
	Ref        string
	Gateway    string
	GatewayRef string
	CustomerID int64
	PlanID     int64
	Amount     int64
	Coupon     string
	Channel    string
	PayUrl     string
	Status     string
	CreatedAt  int64
	PaidAt     sql.NullInt64
	ExpiresAt  int64
	Username   string
	PlanName   string
}

// status ” = any; created_at range: from_ts/to_ts 0 = open. page_limit -1 = all (CSV).
func (q *Queries) SearchPaymentRequests(ctx context.Context, arg SearchPaymentRequestsParams) ([]SearchPaymentRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPaymentRequests,
		arg.Q,
		arg.Status,
		arg.FromTs,
		arg.ToTs,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPaymentRequestsRow
	for rows.Next() {
		var i SearchPaymentRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ref,
			&i.Gateway,
			&i.GatewayRef,
			&i.CustomerID,
			&i.PlanID,
			&i.Amount,
			&i.Coupon,
			&i.Channel,
			&i.PayUrl,
			&i.Status,
			&i.CreatedAt,
			&i.PaidAt,
			&i.ExpiresAt,
			&i.Username,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentGatewayRef = `-- name: SetPaymentGatewayRef :exec
UPDATE payment_requests SET gateway_ref = ?, pay_url = ? WHERE id = ?
`

type SetPaymentGatewayRefParams struct {
	GatewayRef string
	PayUrl     string
	ID         int64
}

func (q *Queries) SetPaymentGatewayRef(ctx context.Context, arg SetPaymentGatewayRefParams) error {
	_, err := q.db.ExecContext(ctx, setPaymentGatewayRef, arg.GatewayRef, arg.PayUrl, arg.ID)
	return err
}
