// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: plans.sql

package db

import (
	"context"
	"database/sql"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (name, type, billing, price, validity, validity_unit, time_limit, time_unit,
                   data_limit, data_unit, shared_users, bandwidth_id, router_id, pool_id, enabled,
                   limited, limit_type, expired_plan_id, billing_day, on_login, on_logout, device)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, type, billing, price, validity, validity_unit, limited, limit_type, time_limit, time_unit, data_limit, data_unit, shared_users, bandwidth_id, router_id, pool_id, expired_plan_id, billing_day, on_login, on_logout, device, enabled
`

type CreatePlanParams struct {
	Name          string
	Type          string
	Billing       string
	Price         int64
	Validity      int64
	ValidityUnit  string
	TimeLimit     sql.NullInt64
	TimeUnit      sql.NullString
	DataLimit     sql.NullInt64
	DataUnit      sql.NullString
	SharedUsers   sql.NullInt64
	BandwidthID   sql.NullInt64
	RouterID      sql.NullInt64
	PoolID        sql.NullInt64
	Enabled       int64
	Limited       int64
	LimitType     sql.NullString
	ExpiredPlanID sql.NullInt64
	BillingDay    sql.NullInt64
	OnLogin       string
	OnLogout      string
	Device        string
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, createPlan,
		arg.Name,
		arg.Type,
		arg.Billing,
		arg.Price,
		arg.Validity,
		arg.ValidityUnit,
		arg.TimeLimit,
		arg.TimeUnit,
		arg.DataLimit,
		arg.DataUnit,
		arg.SharedUsers,
		arg.BandwidthID,
		arg.RouterID,
		arg.PoolID,
		arg.Enabled,
		arg.Limited,
		arg.LimitType,
		arg.ExpiredPlanID,
		arg.BillingDay,
		arg.OnLogin,
		arg.OnLogout,
		arg.Device,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Billing,
		&i.Price,
		&i.Validity,
		&i.ValidityUnit,
		&i.Limited,
		&i.LimitType,
		&i.TimeLimit,
		&i.TimeUnit,
		&i.DataLimit,
		&i.DataUnit,
		&i.SharedUsers,
		&i.BandwidthID,
		&i.RouterID,
		&i.PoolID,
		&i.ExpiredPlanID,
		&i.BillingDay,
		&i.OnLogin,
		&i.OnLogout,
		&i.Device,
		&i.Enabled,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = ?
`

func (q *Queries) DeletePlan(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlan, id)
	return err
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, type, billing, price, validity, validity_unit, limited, limit_type, time_limit, time_unit, data_limit, data_unit, shared_users, bandwidth_id, router_id, pool_id, expired_plan_id, billing_day, on_login, on_logout, device, enabled FROM plans WHERE id = ?
`

func (q *Queries) GetPlan(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Billing,
		&i.Price,
		&i.Validity,
		&i.ValidityUnit,
		&i.Limited,
		&i.LimitType,
		&i.TimeLimit,
		&i.TimeUnit,
		&i.DataLimit,
		&i.DataUnit,
		&i.SharedUsers,
		&i.BandwidthID,
		&i.RouterID,
		&i.PoolID,
		&i.ExpiredPlanID,
		&i.BillingDay,
		&i.OnLogin,
		&i.OnLogout,
		&i.Device,
		&i.Enabled,
	)
	return i, err
}

const listEnabledPlansByType = `-- name: ListEnabledPlansByType :many
SELECT id, name, type, billing, price, validity, validity_unit, limited, limit_type, time_limit, time_unit, data_limit, data_unit, shared_users, bandwidth_id, router_id, pool_id, expired_plan_id, billing_day, on_login, on_logout, device, enabled FROM plans WHERE enabled = 1 AND type = ? ORDER BY price
`

func (q *Queries) ListEnabledPlansByType(ctx context.Context, type_ string) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPlansByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Billing,
			&i.Price,
			&i.Validity,
			&i.ValidityUnit,
			&i.Limited,
			&i.LimitType,
			&i.TimeLimit,
			&i.TimeUnit,
			&i.DataLimit,
			&i.DataUnit,
			&i.SharedUsers,
			&i.BandwidthID,
			&i.RouterID,
			&i.PoolID,
			&i.ExpiredPlanID,
			&i.BillingDay,
			&i.OnLogin,
			&i.OnLogout,
			&i.Device,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, type, billing, price, validity, validity_unit, limited, limit_type, time_limit, time_unit, data_limit, data_unit, shared_users, bandwidth_id, router_id, pool_id, expired_plan_id, billing_day, on_login, on_logout, device, enabled FROM plans ORDER BY name LIMIT ? OFFSET ?
`

type ListPlansParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Billing,
			&i.Price,
			&i.Validity,
			&i.ValidityUnit,
			&i.Limited,
			&i.LimitType,
			&i.TimeLimit,
			&i.TimeUnit,
			&i.DataLimit,
			&i.DataUnit,
			&i.SharedUsers,
			&i.BandwidthID,
			&i.RouterID,
			&i.PoolID,
			&i.ExpiredPlanID,
			&i.BillingDay,
			&i.OnLogin,
			&i.OnLogout,
			&i.Device,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlans = `-- name: SearchPlans :many
SELECT id, name, type, billing, price, validity, validity_unit, limited, limit_type, time_limit, time_unit, data_limit, data_unit, shared_users, bandwidth_id, router_id, pool_id, expired_plan_id, billing_day, on_login, on_logout, device, enabled FROM plans WHERE name LIKE '%' || CAST(?1 AS TEXT) || '%' ORDER BY name LIMIT ?3 OFFSET ?2
`

type SearchPlansParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchPlans(ctx context.Context, arg SearchPlansParams) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, searchPlans, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Billing,
			&i.Price,
			&i.Validity,
			&i.ValidityUnit,
			&i.Limited,
			&i.LimitType,
			&i.TimeLimit,
			&i.TimeUnit,
			&i.DataLimit,
			&i.DataUnit,
			&i.SharedUsers,
			&i.BandwidthID,
			&i.RouterID,
			&i.PoolID,
			&i.ExpiredPlanID,
			&i.BillingDay,
			&i.OnLogin,
			&i.OnLogout,
			&i.Device,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans SET name = ?, type = ?, billing = ?, price = ?, validity = ?, validity_unit = ?,
    time_limit = ?, time_unit = ?, data_limit = ?, data_unit = ?, shared_users = ?,
    bandwidth_id = ?, router_id = ?, pool_id = ?, enabled = ?,
    limited = ?, limit_type = ?, expired_plan_id = ?, billing_day = ?, on_login = ?, on_logout = ?, device = ?
WHERE id = ?
`

type UpdatePlanParams struct {
	Name          string
	Type          string
	Billing       string
	Price         int64
	Validity      int64
	ValidityUnit  string
	TimeLimit     sql.NullInt64
	TimeUnit      sql.NullString
	DataLimit     sql.NullInt64
	DataUnit      sql.NullString
	SharedUsers   sql.NullInt64
	BandwidthID   sql.NullInt64
	RouterID      sql.NullInt64
	PoolID        sql.NullInt64
	Enabled       int64
	Limited       int64
	LimitType     sql.NullString
	ExpiredPlanID sql.NullInt64
	BillingDay    sql.NullInt64
	OnLogin       string
	OnLogout      string
	Device        string
	ID            int64
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.ExecContext(ctx, updatePlan,
		arg.Name,
		arg.Type,
		arg.Billing,
		arg.Price,
		arg.Validity,
		arg.ValidityUnit,
		arg.TimeLimit,
		arg.TimeUnit,
		arg.DataLimit,
		arg.DataUnit,
		arg.SharedUsers,
		arg.BandwidthID,
		arg.RouterID,
		arg.PoolID,
		arg.Enabled,
		arg.Limited,
		arg.LimitType,
		arg.ExpiredPlanID,
		arg.BillingDay,
		arg.OnLogin,
		arg.OnLogout,
		arg.Device,
		arg.ID,
	)
	return err
}
