// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pools.sql

package db

import (
	"context"
)

const createPool = `-- name: CreatePool :one
INSERT INTO pools (name, local_ip, range_ip, router_id) VALUES (?, ?, ?, ?)
RETURNING id, name, local_ip, range_ip, router_id
`

type CreatePoolParams struct {
	Name     string
	LocalIp  string
	RangeIp  string
	RouterID int64
}

func (q *Queries) CreatePool(ctx context.Context, arg CreatePoolParams) (Pool, error) {
	row := q.db.QueryRowContext(ctx, createPool,
		arg.Name,
		arg.LocalIp,
		arg.RangeIp,
		arg.RouterID,
	)
	var i Pool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocalIp,
		&i.RangeIp,
		&i.RouterID,
	)
	return i, err
}

const deletePool = `-- name: DeletePool :exec
DELETE FROM pools WHERE id = ?
`

func (q *Queries) DeletePool(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePool, id)
	return err
}

const getPool = `-- name: GetPool :one
SELECT id, name, local_ip, range_ip, router_id FROM pools WHERE id = ?
`

func (q *Queries) GetPool(ctx context.Context, id int64) (Pool, error) {
	row := q.db.QueryRowContext(ctx, getPool, id)
	var i Pool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocalIp,
		&i.RangeIp,
		&i.RouterID,
	)
	return i, err
}

const listPools = `-- name: ListPools :many
SELECT id, name, local_ip, range_ip, router_id FROM pools ORDER BY name LIMIT ? OFFSET ?
`

type ListPoolsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListPools(ctx context.Context, arg ListPoolsParams) ([]Pool, error) {
	rows, err := q.db.QueryContext(ctx, listPools, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pool
	for rows.Next() {
		var i Pool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LocalIp,
			&i.RangeIp,
			&i.RouterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolsByRouter = `-- name: ListPoolsByRouter :many
SELECT id, name, local_ip, range_ip, router_id FROM pools WHERE router_id = ? ORDER BY name
`

func (q *Queries) ListPoolsByRouter(ctx context.Context, routerID int64) ([]Pool, error) {
	rows, err := q.db.QueryContext(ctx, listPoolsByRouter, routerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pool
	for rows.Next() {
		var i Pool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LocalIp,
			&i.RangeIp,
			&i.RouterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPools = `-- name: SearchPools :many
SELECT id, name, local_ip, range_ip, router_id FROM pools WHERE name LIKE '%' || CAST(?1 AS TEXT) || '%' ORDER BY name LIMIT ?3 OFFSET ?2
`

type SearchPoolsParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchPools(ctx context.Context, arg SearchPoolsParams) ([]Pool, error) {
	rows, err := q.db.QueryContext(ctx, searchPools, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pool
	for rows.Next() {
		var i Pool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LocalIp,
			&i.RangeIp,
			&i.RouterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePool = `-- name: UpdatePool :exec
UPDATE pools SET name = ?, local_ip = ?, range_ip = ?, router_id = ? WHERE id = ?
`

type UpdatePoolParams struct {
	Name     string
	LocalIp  string
	RangeIp  string
	RouterID int64
	ID       int64
}

func (q *Queries) UpdatePool(ctx context.Context, arg UpdatePoolParams) error {
	_, err := q.db.ExecContext(ctx, updatePool,
		arg.Name,
		arg.LocalIp,
		arg.RangeIp,
		arg.RouterID,
		arg.ID,
	)
	return err
}
