// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: radius.sql

package db

import (
	"context"
	"database/sql"
)

const closeRadiusSessionsByNAS = `-- name: CloseRadiusSessionsByNAS :exec
UPDATE radius_sessions SET stopped_at = ? WHERE nas_ip = ? AND stopped_at IS NULL
`

type CloseRadiusSessionsByNASParams struct {
	StoppedAt sql.NullInt64
	NasIp     string
}

func (q *Queries) CloseRadiusSessionsByNAS(ctx context.Context, arg CloseRadiusSessionsByNASParams) error {
	_, err := q.db.ExecContext(ctx, closeRadiusSessionsByNAS, arg.StoppedAt, arg.NasIp)
	return err
}

const countOtherOpenRadiusSessions = `-- name: CountOtherOpenRadiusSessions :one
SELECT COUNT(*) FROM radius_sessions
WHERE username = ? AND stopped_at IS NULL AND updated_at >= ?
  AND (framed_ip <> ? OR ? = '')
  AND (mac <> ? OR ? = '')
`

type CountOtherOpenRadiusSessionsParams struct {
	Username  string
	UpdatedAt int64
	FramedIp  string
	Column4   interface{}
	Mac       string
	Column6   interface{}
}

// Open, recently updated sessions of the user that are not the requesting device (same framed IP or MAC).
func (q *Queries) CountOtherOpenRadiusSessions(ctx context.Context, arg CountOtherOpenRadiusSessionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOtherOpenRadiusSessions,
		arg.Username,
		arg.UpdatedAt,
		arg.FramedIp,
		arg.Column4,
		arg.Mac,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNAS = `-- name: CreateNAS :one
INSERT INTO nas (name, ip, secret_enc, description) VALUES (?, ?, ?, ?) RETURNING id, name, ip, secret_enc, description
`

type CreateNASParams struct {
	Name        string
	Ip          string
	SecretEnc   []byte
	Description string
}

func (q *Queries) CreateNAS(ctx context.Context, arg CreateNASParams) (Na, error) {
	row := q.db.QueryRowContext(ctx, createNAS,
		arg.Name,
		arg.Ip,
		arg.SecretEnc,
		arg.Description,
	)
	var i Na
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.SecretEnc,
		&i.Description,
	)
	return i, err
}

const deleteNAS = `-- name: DeleteNAS :exec
DELETE FROM nas WHERE id = ?
`

func (q *Queries) DeleteNAS(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNAS, id)
	return err
}

const getCustomerForRadius = `-- name: GetCustomerForRadius :one
SELECT id, username, password_hash, fullname, address, phone, email, balance, service_type, pppoe_username, pppoe_ip, secret_enc, billing_day, auto_renewal, status, created_by, created_at, last_login_at, coordinates FROM customers
WHERE (username = ?1 OR (pppoe_username <> '' AND pppoe_username = ?1)) AND status = 'Active'
LIMIT 1
`

func (q *Queries) GetCustomerForRadius(ctx context.Context, name string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerForRadius, name)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Fullname,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Balance,
		&i.ServiceType,
		&i.PppoeUsername,
		&i.PppoeIp,
		&i.SecretEnc,
		&i.BillingDay,
		&i.AutoRenewal,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Coordinates,
	)
	return i, err
}

const getNAS = `-- name: GetNAS :one
SELECT id, name, ip, secret_enc, description FROM nas WHERE id = ?
`

func (q *Queries) GetNAS(ctx context.Context, id int64) (Na, error) {
	row := q.db.QueryRowContext(ctx, getNAS, id)
	var i Na
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.SecretEnc,
		&i.Description,
	)
	return i, err
}

const getRadiusPlan = `-- name: GetRadiusPlan :one
SELECT s.started_at, s.expires_at, p.name AS plan_name, p.type AS plan_type, p.limited, p.limit_type,
       p.time_limit, p.time_unit, p.data_limit, p.data_unit, p.shared_users,
       b.rate_down, b.rate_down_unit, b.rate_up, b.rate_up_unit, b.burst,
       pl.name AS pool_name
FROM subscriptions s
JOIN plans p ON p.id = s.plan_id
LEFT JOIN bandwidths b ON b.id = p.bandwidth_id
LEFT JOIN pools pl ON pl.id = p.pool_id
WHERE s.customer_id = ? AND s.status = 'active'
ORDER BY s.expires_at DESC LIMIT 1
`

type GetRadiusPlanRow struct {
	StartedAt    int64
	ExpiresAt    int64
	PlanName     string
	PlanType     string
	Limited      int64
	LimitType    sql.NullString
	TimeLimit    sql.NullInt64
	TimeUnit     sql.NullString
	DataLimit    sql.NullInt64
	DataUnit     sql.NullString
	SharedUsers  sql.NullInt64
	RateDown     sql.NullInt64
	RateDownUnit sql.NullString
	RateUp       sql.NullInt64
	RateUpUnit   sql.NullString
	Burst        sql.NullString
	PoolName     sql.NullString
}

func (q *Queries) GetRadiusPlan(ctx context.Context, customerID int64) (GetRadiusPlanRow, error) {
	row := q.db.QueryRowContext(ctx, getRadiusPlan, customerID)
	var i GetRadiusPlanRow
	err := row.Scan(
		&i.StartedAt,
		&i.ExpiresAt,
		&i.PlanName,
		&i.PlanType,
		&i.Limited,
		&i.LimitType,
		&i.TimeLimit,
		&i.TimeUnit,
		&i.DataLimit,
		&i.DataUnit,
		&i.SharedUsers,
		&i.RateDown,
		&i.RateDownUnit,
		&i.RateUp,
		&i.RateUpUnit,
		&i.Burst,
		&i.PoolName,
	)
	return i, err
}

const getRadiusSession = `-- name: GetRadiusSession :one
SELECT id, session_id, username, nas_ip, framed_ip, mac, started_at, updated_at, stopped_at, input_octets, output_octets FROM radius_sessions WHERE id = ?
`

func (q *Queries) GetRadiusSession(ctx context.Context, id int64) (RadiusSession, error) {
	row := q.db.QueryRowContext(ctx, getRadiusSession, id)
	var i RadiusSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Username,
		&i.NasIp,
		&i.FramedIp,
		&i.Mac,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.StoppedAt,
		&i.InputOctets,
		&i.OutputOctets,
	)
	return i, err
}

const listNAS = `-- name: ListNAS :many
SELECT id, name, ip, secret_enc, description FROM nas ORDER BY name
`

func (q *Queries) ListNAS(ctx context.Context) ([]Na, error) {
	rows, err := q.db.QueryContext(ctx, listNAS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Na
	for rows.Next() {
		var i Na
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ip,
			&i.SecretEnc,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenRadiusSessionsByUser = `-- name: ListOpenRadiusSessionsByUser :many
SELECT id, session_id, username, nas_ip, framed_ip, mac, started_at, updated_at, stopped_at, input_octets, output_octets FROM radius_sessions WHERE username = ? AND stopped_at IS NULL
`

func (q *Queries) ListOpenRadiusSessionsByUser(ctx context.Context, username string) ([]RadiusSession, error) {
	rows, err := q.db.QueryContext(ctx, listOpenRadiusSessionsByUser, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RadiusSession
	for rows.Next() {
		var i RadiusSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Username,
			&i.NasIp,
			&i.FramedIp,
			&i.Mac,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.StoppedAt,
			&i.InputOctets,
			&i.OutputOctets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRadiusSessionsByUser = `-- name: ListRecentRadiusSessionsByUser :many
SELECT id, session_id, username, nas_ip, framed_ip, mac, started_at, updated_at, stopped_at, input_octets, output_octets FROM radius_sessions WHERE username = ? ORDER BY started_at DESC LIMIT 10
`

func (q *Queries) ListRecentRadiusSessionsByUser(ctx context.Context, username string) ([]RadiusSession, error) {
	rows, err := q.db.QueryContext(ctx, listRecentRadiusSessionsByUser, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RadiusSession
	for rows.Next() {
		var i RadiusSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Username,
			&i.NasIp,
			&i.FramedIp,
			&i.Mac,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.StoppedAt,
			&i.InputOctets,
			&i.OutputOctets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOpenRadiusSessions = `-- name: SearchOpenRadiusSessions :many
SELECT id, session_id, username, nas_ip, framed_ip, mac, started_at, updated_at, stopped_at, input_octets, output_octets FROM radius_sessions
WHERE stopped_at IS NULL
  AND (username LIKE '%' || CAST(?1 AS TEXT) || '%' OR framed_ip LIKE '%' || CAST(?1 AS TEXT) || '%' OR mac LIKE '%' || CAST(?1 AS TEXT) || '%')
ORDER BY started_at DESC LIMIT ?3 OFFSET ?2
`

type SearchOpenRadiusSessionsParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchOpenRadiusSessions(ctx context.Context, arg SearchOpenRadiusSessionsParams) ([]RadiusSession, error) {
	rows, err := q.db.QueryContext(ctx, searchOpenRadiusSessions, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RadiusSession
	for rows.Next() {
		var i RadiusSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Username,
			&i.NasIp,
			&i.FramedIp,
			&i.Mac,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.StoppedAt,
			&i.InputOctets,
			&i.OutputOctets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumRadiusUsage = `-- name: SumRadiusUsage :one
SELECT CAST(COALESCE(SUM(input_octets + output_octets), 0) AS INTEGER) FROM radius_sessions
WHERE username = ? AND started_at >= ?
`

type SumRadiusUsageParams struct {
	Username  string
	StartedAt int64
}

func (q *Queries) SumRadiusUsage(ctx context.Context, arg SumRadiusUsageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumRadiusUsage, arg.Username, arg.StartedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateNAS = `-- name: UpdateNAS :exec
UPDATE nas SET name = ?, ip = ?, secret_enc = ?, description = ? WHERE id = ?
`

type UpdateNASParams struct {
	Name        string
	Ip          string
	SecretEnc   []byte
	Description string
	ID          int64
}

func (q *Queries) UpdateNAS(ctx context.Context, arg UpdateNASParams) error {
	_, err := q.db.ExecContext(ctx, updateNAS,
		arg.Name,
		arg.Ip,
		arg.SecretEnc,
		arg.Description,
		arg.ID,
	)
	return err
}

const upsertRadiusSession = `-- name: UpsertRadiusSession :exec
INSERT INTO radius_sessions (session_id, username, nas_ip, framed_ip, mac, started_at, updated_at, stopped_at, input_octets, output_octets)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (nas_ip, session_id) DO UPDATE SET
    framed_ip = excluded.framed_ip, updated_at = excluded.updated_at,
    stopped_at = COALESCE(radius_sessions.stopped_at, excluded.stopped_at),
    input_octets = excluded.input_octets, output_octets = excluded.output_octets
`

type UpsertRadiusSessionParams struct {
	SessionID    string
	Username     string
	NasIp        string
	FramedIp     string
	Mac          string
	StartedAt    int64
	UpdatedAt    int64
	StoppedAt    sql.NullInt64
	InputOctets  int64
	OutputOctets int64
}

func (q *Queries) UpsertRadiusSession(ctx context.Context, arg UpsertRadiusSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertRadiusSession,
		arg.SessionID,
		arg.Username,
		arg.NasIp,
		arg.FramedIp,
		arg.Mac,
		arg.StartedAt,
		arg.UpdatedAt,
		arg.StoppedAt,
		arg.InputOctets,
		arg.OutputOctets,
	)
	return err
}
