// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reports.sql

package db

import (
	"context"
)

const reportTransactions = `-- name: ReportTransactions :many
SELECT id, invoice, customer_id, plan_id, username, plan_name, router_name, type, price, method, note, admin_id, created_at, period_start, period_end FROM transactions
WHERE created_at >= ?1 AND created_at < ?2
  AND (CAST(?3 AS TEXT) = '' OR type = ?3)
  AND (CAST(?4 AS TEXT) = '' OR method = ?4)
  AND (CAST(?5 AS TEXT) = '' OR router_name = ?5)
  AND (CAST(?6 AS INTEGER) = 0 OR plan_id = ?6)
  AND NOT (method = 'Customer - Balance' AND type = 'Balance')
ORDER BY created_at, id
`

type ReportTransactionsParams struct {
	FromTs     int64
	ToTs       int64
	Type       string
	Method     string
	RouterName string
	PlanID     int64
}

// Empty / zero filter args match everything.
func (q *Queries) ReportTransactions(ctx context.Context, arg ReportTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, reportTransactions,
		arg.FromTs,
		arg.ToTs,
		arg.Type,
		arg.Method,
		arg.RouterName,
		arg.PlanID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Invoice,
			&i.CustomerID,
			&i.PlanID,
			&i.Username,
			&i.PlanName,
			&i.RouterName,
			&i.Type,
			&i.Price,
			&i.Method,
			&i.Note,
			&i.AdminID,
			&i.CreatedAt,
			&i.PeriodStart,
			&i.PeriodEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
