// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: routers.sql

package db

import (
	"context"
	"database/sql"
)

const createRouter = `-- name: CreateRouter :one
INSERT INTO routers (name, host, port, username, password_enc, description, enabled, coordinates, coverage)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, host, port, username, password_enc, description, enabled, coordinates, coverage, last_seen_at, online
`

type CreateRouterParams struct {
	Name        string
	Host        string
	Port        int64
	Username    string
	PasswordEnc []byte
	Description string
	Enabled     int64
	Coordinates string
	Coverage    int64
}

func (q *Queries) CreateRouter(ctx context.Context, arg CreateRouterParams) (Router, error) {
	row := q.db.QueryRowContext(ctx, createRouter,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEnc,
		arg.Description,
		arg.Enabled,
		arg.Coordinates,
		arg.Coverage,
	)
	var i Router
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEnc,
		&i.Description,
		&i.Enabled,
		&i.Coordinates,
		&i.Coverage,
		&i.LastSeenAt,
		&i.Online,
	)
	return i, err
}

const deleteRouter = `-- name: DeleteRouter :exec
DELETE FROM routers WHERE id = ?
`

func (q *Queries) DeleteRouter(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRouter, id)
	return err
}

const getRouter = `-- name: GetRouter :one
SELECT id, name, host, port, username, password_enc, description, enabled, coordinates, coverage, last_seen_at, online FROM routers WHERE id = ?
`

func (q *Queries) GetRouter(ctx context.Context, id int64) (Router, error) {
	row := q.db.QueryRowContext(ctx, getRouter, id)
	var i Router
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEnc,
		&i.Description,
		&i.Enabled,
		&i.Coordinates,
		&i.Coverage,
		&i.LastSeenAt,
		&i.Online,
	)
	return i, err
}

const listEnabledRouters = `-- name: ListEnabledRouters :many
SELECT id, name, host, port, username, password_enc, description, enabled, coordinates, coverage, last_seen_at, online FROM routers WHERE enabled = 1 ORDER BY name
`

func (q *Queries) ListEnabledRouters(ctx context.Context) ([]Router, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledRouters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Router
	for rows.Next() {
		var i Router
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.PasswordEnc,
			&i.Description,
			&i.Enabled,
			&i.Coordinates,
			&i.Coverage,
			&i.LastSeenAt,
			&i.Online,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfflineRouters = `-- name: ListOfflineRouters :many
SELECT id, name, host, port, username, password_enc, description, enabled, coordinates, coverage, last_seen_at, online FROM routers WHERE enabled = 1 AND online = 0 ORDER BY name
`

func (q *Queries) ListOfflineRouters(ctx context.Context) ([]Router, error) {
	rows, err := q.db.QueryContext(ctx, listOfflineRouters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Router
	for rows.Next() {
		var i Router
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.PasswordEnc,
			&i.Description,
			&i.Enabled,
			&i.Coordinates,
			&i.Coverage,
			&i.LastSeenAt,
			&i.Online,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouters = `-- name: ListRouters :many
SELECT id, name, host, port, username, password_enc, description, enabled, coordinates, coverage, last_seen_at, online FROM routers ORDER BY name LIMIT ? OFFSET ?
`

type ListRoutersParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListRouters(ctx context.Context, arg ListRoutersParams) ([]Router, error) {
	rows, err := q.db.QueryContext(ctx, listRouters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Router
	for rows.Next() {
		var i Router
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.PasswordEnc,
			&i.Description,
			&i.Enabled,
			&i.Coordinates,
			&i.Coverage,
			&i.LastSeenAt,
			&i.Online,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRouters = `-- name: SearchRouters :many
SELECT id, name, host, port, username, password_enc, description, enabled, coordinates, coverage, last_seen_at, online FROM routers
WHERE name LIKE '%' || CAST(?1 AS TEXT) || '%' OR host LIKE '%' || CAST(?1 AS TEXT) || '%'
ORDER BY name LIMIT ?3 OFFSET ?2
`

type SearchRoutersParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchRouters(ctx context.Context, arg SearchRoutersParams) ([]Router, error) {
	rows, err := q.db.QueryContext(ctx, searchRouters, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Router
	for rows.Next() {
		var i Router
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.Username,
			&i.PasswordEnc,
			&i.Description,
			&i.Enabled,
			&i.Coordinates,
			&i.Coverage,
			&i.LastSeenAt,
			&i.Online,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRouterStatus = `-- name: SetRouterStatus :exec
UPDATE routers SET online = ?, last_seen_at = COALESCE(?, last_seen_at) WHERE id = ?
`

type SetRouterStatusParams struct {
	Online     sql.NullInt64
	LastSeenAt sql.NullInt64
	ID         int64
}

func (q *Queries) SetRouterStatus(ctx context.Context, arg SetRouterStatusParams) error {
	_, err := q.db.ExecContext(ctx, setRouterStatus, arg.Online, arg.LastSeenAt, arg.ID)
	return err
}

const updateRouter = `-- name: UpdateRouter :exec
UPDATE routers SET name = ?, host = ?, port = ?, username = ?, password_enc = ?, description = ?, enabled = ?, coordinates = ?, coverage = ?
WHERE id = ?
`

type UpdateRouterParams struct {
	Name        string
	Host        string
	Port        int64
	Username    string
	PasswordEnc []byte
	Description string
	Enabled     int64
	Coordinates string
	Coverage    int64
	ID          int64
}

func (q *Queries) UpdateRouter(ctx context.Context, arg UpdateRouterParams) error {
	_, err := q.db.ExecContext(ctx, updateRouter,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEnc,
		arg.Description,
		arg.Enabled,
		arg.Coordinates,
		arg.Coverage,
		arg.ID,
	)
	return err
}
