// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: search.sql

package db

import (
	"context"
)

const searchCustomersContains = `-- name: SearchCustomersContains :many

SELECT id, username, fullname, phone, pppoe_username, email, status FROM customers
WHERE instr(lower(username), lower(?1)) > 0 OR instr(lower(fullname), lower(?1)) > 0
   OR instr(lower(phone), lower(?1)) > 0 OR instr(lower(pppoe_username), lower(?1)) > 0
   OR instr(lower(email), lower(?1)) > 0
ORDER BY username LIMIT ?2
`

type SearchCustomersContainsParams struct {
	Q     string
	Limit int64
}

type SearchCustomersContainsRow struct {
	ID            int64
	Username      string
	Fullname      string
	Phone         string
	PppoeUsername string
	Email         string
	Status        string
}

// Header search palette (internal/web/admin_search.go). The text is matched literally with instr/substr,
// so % and _ are plain characters (sqlc's SQLite parser does not take LIKE ... ESCAPE). Case-insensitive.
func (q *Queries) SearchCustomersContains(ctx context.Context, arg SearchCustomersContainsParams) ([]SearchCustomersContainsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCustomersContains, arg.Q, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCustomersContainsRow
	for rows.Next() {
		var i SearchCustomersContainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Fullname,
			&i.Phone,
			&i.PppoeUsername,
			&i.Email,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNASContains = `-- name: SearchNASContains :many
SELECT id, name, ip FROM nas
WHERE instr(lower(name), lower(?1)) > 0 OR instr(lower(ip), lower(?1)) > 0
ORDER BY name LIMIT ?2
`

type SearchNASContainsParams struct {
	Q     string
	Limit int64
}

type SearchNASContainsRow struct {
	ID   int64
	Name string
	Ip   string
}

func (q *Queries) SearchNASContains(ctx context.Context, arg SearchNASContainsParams) ([]SearchNASContainsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchNASContains, arg.Q, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNASContainsRow
	for rows.Next() {
		var i SearchNASContainsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Ip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlansContains = `-- name: SearchPlansContains :many
SELECT id, name, type, price FROM plans WHERE instr(lower(name), lower(?1)) > 0 ORDER BY name LIMIT ?2
`

type SearchPlansContainsParams struct {
	Q     string
	Limit int64
}

type SearchPlansContainsRow struct {
	ID    int64
	Name  string
	Type  string
	Price int64
}

func (q *Queries) SearchPlansContains(ctx context.Context, arg SearchPlansContainsParams) ([]SearchPlansContainsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPlansContains, arg.Q, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPlansContainsRow
	for rows.Next() {
		var i SearchPlansContainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRoutersContains = `-- name: SearchRoutersContains :many
SELECT id, name, host FROM routers
WHERE instr(lower(name), lower(?1)) > 0 OR instr(lower(host), lower(?1)) > 0
ORDER BY name LIMIT ?2
`

type SearchRoutersContainsParams struct {
	Q     string
	Limit int64
}

type SearchRoutersContainsRow struct {
	ID   int64
	Name string
	Host string
}

func (q *Queries) SearchRoutersContains(ctx context.Context, arg SearchRoutersContainsParams) ([]SearchRoutersContainsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchRoutersContains, arg.Q, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRoutersContainsRow
	for rows.Next() {
		var i SearchRoutersContainsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Host); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSubscriptionsByUsername = `-- name: SearchSubscriptionsByUsername :many
SELECT s.id, s.status, s.expires_at, c.id AS customer_id, c.username, p.name AS plan_name
FROM subscriptions s
JOIN customers c ON c.id = s.customer_id
JOIN plans p ON p.id = s.plan_id
WHERE instr(lower(c.username), lower(?1)) > 0
ORDER BY s.id DESC LIMIT ?2
`

type SearchSubscriptionsByUsernameParams struct {
	Q     string
	Limit int64
}

type SearchSubscriptionsByUsernameRow struct {
	ID         int64
	Status     string
	ExpiresAt  int64
	CustomerID int64
	Username   string
	PlanName   string
}

func (q *Queries) SearchSubscriptionsByUsername(ctx context.Context, arg SearchSubscriptionsByUsernameParams) ([]SearchSubscriptionsByUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSubscriptionsByUsername, arg.Q, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSubscriptionsByUsernameRow
	for rows.Next() {
		var i SearchSubscriptionsByUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ExpiresAt,
			&i.CustomerID,
			&i.Username,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransactionsPrefix = `-- name: SearchTransactionsPrefix :many
SELECT id, invoice, username, plan_name, price FROM transactions
WHERE lower(substr(invoice, 1, length(?1))) = lower(?1)
ORDER BY id DESC LIMIT ?2
`

type SearchTransactionsPrefixParams struct {
	Q     interface{}
	Limit int64
}

type SearchTransactionsPrefixRow struct {
	ID       int64
	Invoice  string
	Username string
	PlanName string
	Price    int64
}

func (q *Queries) SearchTransactionsPrefix(ctx context.Context, arg SearchTransactionsPrefixParams) ([]SearchTransactionsPrefixRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTransactionsPrefix, arg.Q, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTransactionsPrefixRow
	for rows.Next() {
		var i SearchTransactionsPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.Invoice,
			&i.Username,
			&i.PlanName,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVouchersPrefix = `-- name: SearchVouchersPrefix :many
SELECT v.id, v.code, v.status, p.name AS plan_name FROM vouchers v JOIN plans p ON p.id = v.plan_id
WHERE lower(substr(v.code, 1, length(?1))) = lower(?1)
ORDER BY v.id DESC LIMIT ?2
`

type SearchVouchersPrefixParams struct {
	Q     interface{}
	Limit int64
}

type SearchVouchersPrefixRow struct {
	ID       int64
	Code     string
	Status   string
	PlanName string
}

func (q *Queries) SearchVouchersPrefix(ctx context.Context, arg SearchVouchersPrefixParams) ([]SearchVouchersPrefixRow, error) {
	rows, err := q.db.QueryContext(ctx, searchVouchersPrefix, arg.Q, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchVouchersPrefixRow
	for rows.Next() {
		var i SearchVouchersPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Status,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
