// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: subscriptions.sql

package db

import (
	"context"
	"database/sql"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (customer_id, plan_id, router_id, type, started_at, expires_at, method, admin_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id
`

type CreateSubscriptionParams struct {
	CustomerID int64
	PlanID     int64
	RouterID   int64
	Type       string
	StartedAt  int64
	ExpiresAt  int64
	Method     string
	AdminID    sql.NullInt64
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.CustomerID,
		arg.PlanID,
		arg.RouterID,
		arg.Type,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.Method,
		arg.AdminID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PlanID,
		&i.RouterID,
		&i.Type,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Method,
		&i.AdminID,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE id = ?
`

func (q *Queries) DeleteSubscription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, id)
	return err
}

const expireSubscription = `-- name: ExpireSubscription :execrows
UPDATE subscriptions SET status = 'expired' WHERE id = ? AND status = 'active'
`

func (q *Queries) ExpireSubscription(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id FROM subscriptions WHERE id = ?
`

func (q *Queries) GetSubscription(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PlanID,
		&i.RouterID,
		&i.Type,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Method,
		&i.AdminID,
	)
	return i, err
}

const listExpiredActiveSubscriptions = `-- name: ListExpiredActiveSubscriptions :many
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id FROM subscriptions WHERE status = 'active' AND expires_at <= ?1 ORDER BY expires_at
`

func (q *Queries) ListExpiredActiveSubscriptions(ctx context.Context, now int64) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredActiveSubscriptions, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id FROM subscriptions ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListSubscriptionsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByCustomer = `-- name: ListSubscriptionsByCustomer :many
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id FROM subscriptions WHERE customer_id = ? ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListSubscriptionsByCustomerParams struct {
	CustomerID int64
	Limit      int64
	Offset     int64
}

func (q *Queries) ListSubscriptionsByCustomer(ctx context.Context, arg ListSubscriptionsByCustomerParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewSubscription = `-- name: RenewSubscription :exec
UPDATE subscriptions SET plan_id = ?, router_id = ?, type = ?, started_at = ?, expires_at = ?,
    status = 'active', method = ?, admin_id = ?
WHERE id = ?
`

type RenewSubscriptionParams struct {
	PlanID    int64
	RouterID  int64
	Type      string
	StartedAt int64
	ExpiresAt int64
	Method    string
	AdminID   sql.NullInt64
	ID        int64
}

func (q *Queries) RenewSubscription(ctx context.Context, arg RenewSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, renewSubscription,
		arg.PlanID,
		arg.RouterID,
		arg.Type,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.Method,
		arg.AdminID,
		arg.ID,
	)
	return err
}

const searchSubscriptions = `-- name: SearchSubscriptions :many
SELECT s.id, s.customer_id, s.plan_id, s.router_id, s.type, s.started_at, s.expires_at, s.status, s.method, s.admin_id FROM subscriptions s JOIN customers c ON c.id = s.customer_id
WHERE c.username LIKE '%' || CAST(?1 AS TEXT) || '%' OR c.fullname LIKE '%' || CAST(?1 AS TEXT) || '%'
ORDER BY s.id DESC LIMIT ?3 OFFSET ?2
`

type SearchSubscriptionsParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchSubscriptions(ctx context.Context, arg SearchSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, searchSubscriptions, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
