// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: subscriptions.sql

package db

import (
	"context"
	"database/sql"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (customer_id, plan_id, router_id, type, started_at, expires_at, method, admin_id, pending_start)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id, pending_start
`

type CreateSubscriptionParams struct {
	CustomerID   int64
	PlanID       int64
	RouterID     sql.NullInt64
	Type         string
	StartedAt    int64
	ExpiresAt    int64
	Method       string
	AdminID      sql.NullInt64
	PendingStart int64
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.CustomerID,
		arg.PlanID,
		arg.RouterID,
		arg.Type,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.Method,
		arg.AdminID,
		arg.PendingStart,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PlanID,
		&i.RouterID,
		&i.Type,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Method,
		&i.AdminID,
		&i.PendingStart,
	)
	return i, err
}

const deactivateSubscription = `-- name: DeactivateSubscription :execrows
UPDATE subscriptions SET status = 'expired', expires_at = MAX(started_at, ?1) WHERE id = ?2 AND status = 'active'
`

type DeactivateSubscriptionParams struct {
	Now interface{}
	ID  int64
}

// Expires the subscription now (never before it started); 0 rows = already inactive.
func (q *Queries) DeactivateSubscription(ctx context.Context, arg DeactivateSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deactivateSubscription, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireSubscription = `-- name: ExpireSubscription :execrows
UPDATE subscriptions SET status = 'expired' WHERE id = ?1 AND status = 'active' AND pending_start = 0 AND expires_at <= ?2
`

type ExpireSubscriptionParams struct {
	ID  int64
	Now int64
}

func (q *Queries) ExpireSubscription(ctx context.Context, arg ExpireSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireSubscription, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const filterSubscriptions = `-- name: FilterSubscriptions :many
SELECT s.id, s.type, s.started_at, s.expires_at, s.status, s.method, s.pending_start, c.username, p.name AS plan_name,
       CAST(COALESCE(r.name, '') AS TEXT) AS router_name,
       CAST(?1 AS TEXT) AS sort_key -- e.g. expires_asc; anything else = soonest-expiring last first
FROM subscriptions s JOIN customers c ON c.id = s.customer_id JOIN plans p ON p.id = s.plan_id LEFT JOIN routers r ON r.id = s.router_id
WHERE (c.username LIKE '%' || CAST(?2 AS TEXT) || '%' OR c.fullname LIKE '%' || CAST(?2 AS TEXT) || '%'
       OR p.name LIKE '%' || CAST(?2 AS TEXT) || '%')
  AND (CAST(?3 AS TEXT) = '' OR s.status = ?3)
  AND (CAST(?4 AS TEXT) = '' OR s.type = ?4)
  AND (CAST(?5 AS INTEGER) = 0 OR s.router_id = ?5)
  AND (CAST(?6 AS INTEGER) = 0 OR s.plan_id = ?6)
ORDER BY
  CASE WHEN sort_key = 'username_asc' THEN c.username END ASC,
  CASE WHEN sort_key = 'username_desc' THEN c.username END DESC,
  CASE WHEN sort_key = 'plan_asc' THEN p.name END ASC,
  CASE WHEN sort_key = 'plan_desc' THEN p.name END DESC,
  CASE WHEN sort_key = 'created_asc' THEN s.started_at END ASC,
  CASE WHEN sort_key = 'created_desc' THEN s.started_at END DESC,
  CASE WHEN sort_key = 'expires_asc' THEN s.expires_at END ASC,
  s.expires_at DESC, s.id DESC LIMIT ?8 OFFSET ?7
`

type FilterSubscriptionsParams struct {
	Sort       string
	Q          string
	Status     string
	Type       string
	RouterID   int64
	PlanID     int64
	PageOffset int64
	PageLimit  int64
}

type FilterSubscriptionsRow struct {
	ID           int64
	Type         string
	StartedAt    int64
	ExpiresAt    int64
	Status       string
	Method       string
	PendingStart int64
	Username     string
	PlanName     string
	RouterName   string
	SortKey      string
}

// Empty status/type and router_id/plan_id 0 = any.
func (q *Queries) FilterSubscriptions(ctx context.Context, arg FilterSubscriptionsParams) ([]FilterSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, filterSubscriptions,
		arg.Sort,
		arg.Q,
		arg.Status,
		arg.Type,
		arg.RouterID,
		arg.PlanID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterSubscriptionsRow
	for rows.Next() {
		var i FilterSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.PendingStart,
			&i.Username,
			&i.PlanName,
			&i.RouterName,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id, pending_start FROM subscriptions WHERE id = ?
`

func (q *Queries) GetSubscription(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PlanID,
		&i.RouterID,
		&i.Type,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Method,
		&i.AdminID,
		&i.PendingStart,
	)
	return i, err
}

const listActiveExpiringBetween = `-- name: ListActiveExpiringBetween :many
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id, pending_start FROM subscriptions WHERE status = 'active' AND pending_start = 0 AND expires_at >= ?1 AND expires_at < ?2 ORDER BY expires_at
`

type ListActiveExpiringBetweenParams struct {
	FromTs int64
	ToTs   int64
}

func (q *Queries) ListActiveExpiringBetween(ctx context.Context, arg ListActiveExpiringBetweenParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listActiveExpiringBetween, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
			&i.PendingStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSubscriptionsWithPlan = `-- name: ListActiveSubscriptionsWithPlan :many
SELECT s.id, s.plan_id, s.router_id, s.type, s.expires_at, s.pending_start, p.name AS plan_name
FROM subscriptions s JOIN plans p ON p.id = s.plan_id
WHERE s.customer_id = ? AND s.status = 'active' ORDER BY s.expires_at
`

type ListActiveSubscriptionsWithPlanRow struct {
	ID           int64
	PlanID       int64
	RouterID     sql.NullInt64
	Type         string
	ExpiresAt    int64
	PendingStart int64
	PlanName     string
}

// Customer summary: the subscriptions still active (any expiry, as billing treats them) with the plan name.
func (q *Queries) ListActiveSubscriptionsWithPlan(ctx context.Context, customerID int64) ([]ListActiveSubscriptionsWithPlanRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscriptionsWithPlan, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSubscriptionsWithPlanRow
	for rows.Next() {
		var i ListActiveSubscriptionsWithPlanRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.ExpiresAt,
			&i.PendingStart,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredActiveSubscriptions = `-- name: ListExpiredActiveSubscriptions :many
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id, pending_start FROM subscriptions WHERE status = 'active' AND pending_start = 0 AND expires_at <= ?1 ORDER BY expires_at
`

func (q *Queries) ListExpiredActiveSubscriptions(ctx context.Context, now int64) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredActiveSubscriptions, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
			&i.PendingStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByCustomer = `-- name: ListSubscriptionsByCustomer :many
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id, pending_start FROM subscriptions WHERE customer_id = ? ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListSubscriptionsByCustomerParams struct {
	CustomerID int64
	Limit      int64
	Offset     int64
}

func (q *Queries) ListSubscriptionsByCustomer(ctx context.Context, arg ListSubscriptionsByCustomerParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
			&i.PendingStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewSubscription = `-- name: RenewSubscription :exec
UPDATE subscriptions SET plan_id = ?, router_id = ?, type = ?, started_at = ?, expires_at = ?,
    status = 'active', method = ?, admin_id = ?, pending_start = ?
WHERE id = ?
`

type RenewSubscriptionParams struct {
	PlanID       int64
	RouterID     sql.NullInt64
	Type         string
	StartedAt    int64
	ExpiresAt    int64
	Method       string
	AdminID      sql.NullInt64
	PendingStart int64
	ID           int64
}

func (q *Queries) RenewSubscription(ctx context.Context, arg RenewSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, renewSubscription,
		arg.PlanID,
		arg.RouterID,
		arg.Type,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.Method,
		arg.AdminID,
		arg.PendingStart,
		arg.ID,
	)
	return err
}

const restartSubscription = `-- name: RestartSubscription :exec
UPDATE subscriptions SET started_at = ? WHERE id = ?
`

type RestartSubscriptionParams struct {
	StartedAt int64
	ID        int64
}

// A dead subscription brought back to life starts a new usage window (data limit counts from started_at).
func (q *Queries) RestartSubscription(ctx context.Context, arg RestartSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, restartSubscription, arg.StartedAt, arg.ID)
	return err
}

const startPendingSubscription = `-- name: StartPendingSubscription :execrows
UPDATE subscriptions SET pending_start = 0, started_at = ?1, expires_at = ?2 WHERE id = ?3 AND pending_start = 1
`

type StartPendingSubscriptionParams struct {
	StartedAt int64
	ExpiresAt int64
	ID        int64
}

// First RADIUS login of a start_on_first_login subscription: the usage window and expiry start now. 0 rows = already started.
func (q *Queries) StartPendingSubscription(ctx context.Context, arg StartPendingSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startPendingSubscription, arg.StartedAt, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE subscriptions SET plan_id = ?, router_id = ?, type = ?, expires_at = ?, status = ?, admin_id = ? WHERE id = ?
`

type UpdateSubscriptionParams struct {
	PlanID    int64
	RouterID  sql.NullInt64
	Type      string
	ExpiresAt int64
	Status    string
	AdminID   sql.NullInt64
	ID        int64
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscription,
		arg.PlanID,
		arg.RouterID,
		arg.Type,
		arg.ExpiresAt,
		arg.Status,
		arg.AdminID,
		arg.ID,
	)
	return err
}
