// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: subscriptions.sql

package db

import (
	"context"
	"database/sql"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (customer_id, plan_id, router_id, type, started_at, expires_at, method, admin_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id
`

type CreateSubscriptionParams struct {
	CustomerID int64
	PlanID     int64
	RouterID   sql.NullInt64
	Type       string
	StartedAt  int64
	ExpiresAt  int64
	Method     string
	AdminID    sql.NullInt64
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.CustomerID,
		arg.PlanID,
		arg.RouterID,
		arg.Type,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.Method,
		arg.AdminID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PlanID,
		&i.RouterID,
		&i.Type,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Method,
		&i.AdminID,
	)
	return i, err
}

const deactivateSubscription = `-- name: DeactivateSubscription :execrows
UPDATE subscriptions SET status = 'expired', expires_at = MAX(started_at, ?1) WHERE id = ?2 AND status = 'active'
`

type DeactivateSubscriptionParams struct {
	Now interface{}
	ID  int64
}

// Expires the subscription now (never before it started); 0 rows = already inactive.
func (q *Queries) DeactivateSubscription(ctx context.Context, arg DeactivateSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deactivateSubscription, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE id = ?
`

func (q *Queries) DeleteSubscription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, id)
	return err
}

const expireSubscription = `-- name: ExpireSubscription :execrows
UPDATE subscriptions SET status = 'expired' WHERE id = ?1 AND status = 'active' AND expires_at <= ?2
`

type ExpireSubscriptionParams struct {
	ID  int64
	Now int64
}

func (q *Queries) ExpireSubscription(ctx context.Context, arg ExpireSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireSubscription, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const filterSubscriptions = `-- name: FilterSubscriptions :many
SELECT s.id, s.type, s.started_at, s.expires_at, s.status, s.method, c.username, p.name AS plan_name,
       CAST(COALESCE(r.name, '') AS TEXT) AS router_name
FROM subscriptions s JOIN customers c ON c.id = s.customer_id JOIN plans p ON p.id = s.plan_id LEFT JOIN routers r ON r.id = s.router_id
WHERE (c.username LIKE '%' || CAST(?1 AS TEXT) || '%' OR c.fullname LIKE '%' || CAST(?1 AS TEXT) || '%'
       OR p.name LIKE '%' || CAST(?1 AS TEXT) || '%')
  AND (CAST(?2 AS TEXT) = '' OR s.status = ?2)
  AND (CAST(?3 AS TEXT) = '' OR s.type = ?3)
  AND (CAST(?4 AS INTEGER) = 0 OR s.router_id = ?4)
  AND (CAST(?5 AS INTEGER) = 0 OR s.plan_id = ?5)
ORDER BY s.expires_at DESC, s.id DESC LIMIT ?7 OFFSET ?6
`

type FilterSubscriptionsParams struct {
	Q          string
	Status     string
	Type       string
	RouterID   int64
	PlanID     int64
	PageOffset int64
	PageLimit  int64
}

type FilterSubscriptionsRow struct {
	ID         int64
	Type       string
	StartedAt  int64
	ExpiresAt  int64
	Status     string
	Method     string
	Username   string
	PlanName   string
	RouterName string
}

// Empty status/type and router_id/plan_id 0 = any.
func (q *Queries) FilterSubscriptions(ctx context.Context, arg FilterSubscriptionsParams) ([]FilterSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, filterSubscriptions,
		arg.Q,
		arg.Status,
		arg.Type,
		arg.RouterID,
		arg.PlanID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterSubscriptionsRow
	for rows.Next() {
		var i FilterSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.Username,
			&i.PlanName,
			&i.RouterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id FROM subscriptions WHERE id = ?
`

func (q *Queries) GetSubscription(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PlanID,
		&i.RouterID,
		&i.Type,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Method,
		&i.AdminID,
	)
	return i, err
}

const listActiveExpiringBetween = `-- name: ListActiveExpiringBetween :many
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id FROM subscriptions WHERE status = 'active' AND expires_at >= ?1 AND expires_at < ?2 ORDER BY expires_at
`

type ListActiveExpiringBetweenParams struct {
	FromTs int64
	ToTs   int64
}

func (q *Queries) ListActiveExpiringBetween(ctx context.Context, arg ListActiveExpiringBetweenParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listActiveExpiringBetween, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredActiveSubscriptions = `-- name: ListExpiredActiveSubscriptions :many
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id FROM subscriptions WHERE status = 'active' AND expires_at <= ?1 ORDER BY expires_at
`

func (q *Queries) ListExpiredActiveSubscriptions(ctx context.Context, now int64) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredActiveSubscriptions, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id FROM subscriptions ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListSubscriptionsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByCustomer = `-- name: ListSubscriptionsByCustomer :many
SELECT id, customer_id, plan_id, router_id, type, started_at, expires_at, status, method, admin_id FROM subscriptions WHERE customer_id = ? ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListSubscriptionsByCustomerParams struct {
	CustomerID int64
	Limit      int64
	Offset     int64
}

func (q *Queries) ListSubscriptionsByCustomer(ctx context.Context, arg ListSubscriptionsByCustomerParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewSubscription = `-- name: RenewSubscription :exec
UPDATE subscriptions SET plan_id = ?, router_id = ?, type = ?, started_at = ?, expires_at = ?,
    status = 'active', method = ?, admin_id = ?
WHERE id = ?
`

type RenewSubscriptionParams struct {
	PlanID    int64
	RouterID  sql.NullInt64
	Type      string
	StartedAt int64
	ExpiresAt int64
	Method    string
	AdminID   sql.NullInt64
	ID        int64
}

func (q *Queries) RenewSubscription(ctx context.Context, arg RenewSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, renewSubscription,
		arg.PlanID,
		arg.RouterID,
		arg.Type,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.Method,
		arg.AdminID,
		arg.ID,
	)
	return err
}

const searchSubscriptions = `-- name: SearchSubscriptions :many
SELECT s.id, s.customer_id, s.plan_id, s.router_id, s.type, s.started_at, s.expires_at, s.status, s.method, s.admin_id FROM subscriptions s JOIN customers c ON c.id = s.customer_id
WHERE c.username LIKE '%' || CAST(?1 AS TEXT) || '%' OR c.fullname LIKE '%' || CAST(?1 AS TEXT) || '%'
ORDER BY s.id DESC LIMIT ?3 OFFSET ?2
`

type SearchSubscriptionsParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchSubscriptions(ctx context.Context, arg SearchSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, searchSubscriptions, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PlanID,
			&i.RouterID,
			&i.Type,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Method,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE subscriptions SET plan_id = ?, router_id = ?, type = ?, expires_at = ?, status = ?, admin_id = ? WHERE id = ?
`

type UpdateSubscriptionParams struct {
	PlanID    int64
	RouterID  sql.NullInt64
	Type      string
	ExpiresAt int64
	Status    string
	AdminID   sql.NullInt64
	ID        int64
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscription,
		arg.PlanID,
		arg.RouterID,
		arg.Type,
		arg.ExpiresAt,
		arg.Status,
		arg.AdminID,
		arg.ID,
	)
	return err
}
