// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (invoice, customer_id, plan_id, username, plan_name, router_name, type,
                          price, method, note, admin_id, period_start, period_end)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, invoice, customer_id, plan_id, username, plan_name, router_name, type, price, method, note, admin_id, created_at, period_start, period_end
`

type CreateTransactionParams struct {
	Invoice     string
	CustomerID  sql.NullInt64
	PlanID      sql.NullInt64
	Username    string
	PlanName    string
	RouterName  string
	Type        string
	Price       int64
	Method      string
	Note        string
	AdminID     sql.NullInt64
	PeriodStart int64
	PeriodEnd   int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Invoice,
		arg.CustomerID,
		arg.PlanID,
		arg.Username,
		arg.PlanName,
		arg.RouterName,
		arg.Type,
		arg.Price,
		arg.Method,
		arg.Note,
		arg.AdminID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Invoice,
		&i.CustomerID,
		&i.PlanID,
		&i.Username,
		&i.PlanName,
		&i.RouterName,
		&i.Type,
		&i.Price,
		&i.Method,
		&i.Note,
		&i.AdminID,
		&i.CreatedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, invoice, customer_id, plan_id, username, plan_name, router_name, type, price, method, note, admin_id, created_at, period_start, period_end FROM transactions WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Invoice,
		&i.CustomerID,
		&i.PlanID,
		&i.Username,
		&i.PlanName,
		&i.RouterName,
		&i.Type,
		&i.Price,
		&i.Method,
		&i.Note,
		&i.AdminID,
		&i.CreatedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
	)
	return i, err
}

const getTransactionByInvoice = `-- name: GetTransactionByInvoice :one
SELECT id, invoice, customer_id, plan_id, username, plan_name, router_name, type, price, method, note, admin_id, created_at, period_start, period_end FROM transactions WHERE invoice = ?
`

func (q *Queries) GetTransactionByInvoice(ctx context.Context, invoice string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByInvoice, invoice)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Invoice,
		&i.CustomerID,
		&i.PlanID,
		&i.Username,
		&i.PlanName,
		&i.RouterName,
		&i.Type,
		&i.Price,
		&i.Method,
		&i.Note,
		&i.AdminID,
		&i.CreatedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, invoice, customer_id, plan_id, username, plan_name, router_name, type, price, method, note, admin_id, created_at, period_start, period_end FROM transactions ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListTransactionsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Invoice,
			&i.CustomerID,
			&i.PlanID,
			&i.Username,
			&i.PlanName,
			&i.RouterName,
			&i.Type,
			&i.Price,
			&i.Method,
			&i.Note,
			&i.AdminID,
			&i.CreatedAt,
			&i.PeriodStart,
			&i.PeriodEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByCustomer = `-- name: ListTransactionsByCustomer :many
SELECT id, invoice, customer_id, plan_id, username, plan_name, router_name, type, price, method, note, admin_id, created_at, period_start, period_end FROM transactions WHERE customer_id = ? ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListTransactionsByCustomerParams struct {
	CustomerID sql.NullInt64
	Limit      int64
	Offset     int64
}

func (q *Queries) ListTransactionsByCustomer(ctx context.Context, arg ListTransactionsByCustomerParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Invoice,
			&i.CustomerID,
			&i.PlanID,
			&i.Username,
			&i.PlanName,
			&i.RouterName,
			&i.Type,
			&i.Price,
			&i.Method,
			&i.Note,
			&i.AdminID,
			&i.CreatedAt,
			&i.PeriodStart,
			&i.PeriodEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransactions = `-- name: SearchTransactions :many
SELECT id, invoice, customer_id, plan_id, username, plan_name, router_name, type, price, method, note, admin_id, created_at, period_start, period_end, CAST(?1 AS TEXT) AS sort_key -- e.g. date_asc; anything else = newest first
FROM transactions
WHERE invoice LIKE '%' || CAST(?2 AS TEXT) || '%'
   OR username LIKE '%' || CAST(?2 AS TEXT) || '%'
   OR plan_name LIKE '%' || CAST(?2 AS TEXT) || '%'
ORDER BY
  CASE WHEN sort_key = 'date_asc' THEN created_at END ASC,
  CASE WHEN sort_key = 'date_desc' THEN created_at END DESC,
  CASE WHEN sort_key = 'amount_asc' THEN price END ASC,
  CASE WHEN sort_key = 'amount_desc' THEN price END DESC,
  CASE WHEN sort_key = 'username_asc' THEN username END ASC,
  CASE WHEN sort_key = 'username_desc' THEN username END DESC,
  id DESC LIMIT ?4 OFFSET ?3
`

type SearchTransactionsParams struct {
	Sort       string
	Q          string
	PageOffset int64
	PageLimit  int64
}

type SearchTransactionsRow struct {
	ID          int64
	Invoice     string
	CustomerID  sql.NullInt64
	PlanID      sql.NullInt64
	Username    string
	PlanName    string
	RouterName  string
	Type        string
	Price       int64
	Method      string
	Note        string
	AdminID     sql.NullInt64
	CreatedAt   int64
	PeriodStart int64
	PeriodEnd   int64
	SortKey     string
}

func (q *Queries) SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]SearchTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTransactions,
		arg.Sort,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTransactionsRow
	for rows.Next() {
		var i SearchTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Invoice,
			&i.CustomerID,
			&i.PlanID,
			&i.Username,
			&i.PlanName,
			&i.RouterName,
			&i.Type,
			&i.Price,
			&i.Method,
			&i.Note,
			&i.AdminID,
			&i.CreatedAt,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTransactionsBetween = `-- name: SumTransactionsBetween :one
SELECT CAST(COALESCE(SUM(price), 0) AS INTEGER) FROM transactions WHERE created_at >= ? AND created_at < ?
  AND method <> 'Customer - Balance' AND method NOT LIKE 'Balance - Gift from%'
`

type SumTransactionsBetweenParams struct {
	CreatedAt   int64
	CreatedAt_2 int64
}

func (q *Queries) SumTransactionsBetween(ctx context.Context, arg SumTransactionsBetweenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumTransactionsBetween, arg.CreatedAt, arg.CreatedAt_2)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
