// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: vouchers.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createVoucher = `-- name: CreateVoucher :one
INSERT INTO vouchers (code, plan_id, generated_by) VALUES (?, ?, ?)
RETURNING id, code, plan_id, status, used_by, used_at, generated_by, created_at
`

type CreateVoucherParams struct {
	Code        string
	PlanID      int64
	GeneratedBy sql.NullInt64
}

func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error) {
	row := q.db.QueryRowContext(ctx, createVoucher, arg.Code, arg.PlanID, arg.GeneratedBy)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PlanID,
		&i.Status,
		&i.UsedBy,
		&i.UsedAt,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldUsedVouchers = `-- name: DeleteOldUsedVouchers :execrows
DELETE FROM vouchers WHERE status = 'used' AND used_at < ?1
  AND NOT EXISTS (SELECT 1 FROM subscriptions s WHERE s.method = 'Voucher - ' || vouchers.code)
`

// Old PHP remove-voucher: used before the cutoff, unless a subscription still shows "Voucher - CODE" as its method.
func (q *Queries) DeleteOldUsedVouchers(ctx context.Context, cutoff sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldUsedVouchers, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVoucher = `-- name: DeleteVoucher :exec
DELETE FROM vouchers WHERE id = ? AND status = 'unused'
`

func (q *Queries) DeleteVoucher(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVoucher, id)
	return err
}

const deleteVouchersByIDs = `-- name: DeleteVouchersByIDs :execrows
DELETE FROM vouchers WHERE id IN (/*SLICE:ids*/?)
`

// Bulk delete from the list; like old PHP voucher-delete-many, used vouchers may go too (history lives in transactions).
func (q *Queries) DeleteVouchersByIDs(ctx context.Context, ids []int64) (int64, error) {
	query := deleteVouchersByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getVoucher = `-- name: GetVoucher :one
SELECT id, code, plan_id, status, used_by, used_at, generated_by, created_at FROM vouchers WHERE id = ?
`

func (q *Queries) GetVoucher(ctx context.Context, id int64) (Voucher, error) {
	row := q.db.QueryRowContext(ctx, getVoucher, id)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PlanID,
		&i.Status,
		&i.UsedBy,
		&i.UsedAt,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getVoucherByCode = `-- name: GetVoucherByCode :one
SELECT id, code, plan_id, status, used_by, used_at, generated_by, created_at FROM vouchers WHERE code = ?
`

func (q *Queries) GetVoucherByCode(ctx context.Context, code string) (Voucher, error) {
	row := q.db.QueryRowContext(ctx, getVoucherByCode, code)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PlanID,
		&i.Status,
		&i.UsedBy,
		&i.UsedAt,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const lastVoucherUsedBy = `-- name: LastVoucherUsedBy :one
SELECT v.code, p.name AS plan_name FROM vouchers v JOIN plans p ON p.id = v.plan_id
WHERE v.used_by = ? ORDER BY v.used_at DESC, v.id DESC LIMIT 1
`

type LastVoucherUsedByRow struct {
	Code     string
	PlanName string
}

// The voucher a customer redeemed last; a voucher account is one that redeemed a voucher.
func (q *Queries) LastVoucherUsedBy(ctx context.Context, usedBy sql.NullInt64) (LastVoucherUsedByRow, error) {
	row := q.db.QueryRowContext(ctx, lastVoucherUsedBy, usedBy)
	var i LastVoucherUsedByRow
	err := row.Scan(&i.Code, &i.PlanName)
	return i, err
}

const listVouchers = `-- name: ListVouchers :many
SELECT id, code, plan_id, status, used_by, used_at, generated_by, created_at FROM vouchers ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListVouchersParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListVouchers(ctx context.Context, arg ListVouchersParams) ([]Voucher, error) {
	rows, err := q.db.QueryContext(ctx, listVouchers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voucher
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.PlanID,
			&i.Status,
			&i.UsedBy,
			&i.UsedAt,
			&i.GeneratedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVouchers = `-- name: SearchVouchers :many
SELECT id, code, plan_id, status, used_by, used_at, generated_by, created_at FROM vouchers WHERE code LIKE '%' || CAST(?1 AS TEXT) || '%'
  AND (CAST(?2 AS TEXT) = '' OR status = ?2)
  AND (CAST(?3 AS INTEGER) = 0 OR plan_id = ?3)
ORDER BY id DESC LIMIT ?5 OFFSET ?4
`

type SearchVouchersParams struct {
	Q          string
	Status     string
	PlanID     int64
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchVouchers(ctx context.Context, arg SearchVouchersParams) ([]Voucher, error) {
	rows, err := q.db.QueryContext(ctx, searchVouchers,
		arg.Q,
		arg.Status,
		arg.PlanID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voucher
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.PlanID,
			&i.Status,
			&i.UsedBy,
			&i.UsedAt,
			&i.GeneratedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useVoucher = `-- name: UseVoucher :execrows
UPDATE vouchers SET status = 'used', used_by = ?, used_at = unixepoch()
WHERE id = ? AND status = 'unused'
`

type UseVoucherParams struct {
	UsedBy sql.NullInt64
	ID     int64
}

// Returns 1 if claimed, 0 if already used or missing.
func (q *Queries) UseVoucher(ctx context.Context, arg UseVoucherParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useVoucher, arg.UsedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
