// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: vouchers.sql

package db

import (
	"context"
	"database/sql"
)

const createVoucher = `-- name: CreateVoucher :one
INSERT INTO vouchers (code, plan_id, generated_by) VALUES (?, ?, ?)
RETURNING id, code, plan_id, status, used_by, used_at, generated_by, created_at
`

type CreateVoucherParams struct {
	Code        string
	PlanID      int64
	GeneratedBy sql.NullInt64
}

func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error) {
	row := q.db.QueryRowContext(ctx, createVoucher, arg.Code, arg.PlanID, arg.GeneratedBy)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PlanID,
		&i.Status,
		&i.UsedBy,
		&i.UsedAt,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVoucher = `-- name: DeleteVoucher :exec
DELETE FROM vouchers WHERE id = ? AND status = 'unused'
`

func (q *Queries) DeleteVoucher(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVoucher, id)
	return err
}

const getVoucher = `-- name: GetVoucher :one
SELECT id, code, plan_id, status, used_by, used_at, generated_by, created_at FROM vouchers WHERE id = ?
`

func (q *Queries) GetVoucher(ctx context.Context, id int64) (Voucher, error) {
	row := q.db.QueryRowContext(ctx, getVoucher, id)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PlanID,
		&i.Status,
		&i.UsedBy,
		&i.UsedAt,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getVoucherByCode = `-- name: GetVoucherByCode :one
SELECT id, code, plan_id, status, used_by, used_at, generated_by, created_at FROM vouchers WHERE code = ?
`

func (q *Queries) GetVoucherByCode(ctx context.Context, code string) (Voucher, error) {
	row := q.db.QueryRowContext(ctx, getVoucherByCode, code)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PlanID,
		&i.Status,
		&i.UsedBy,
		&i.UsedAt,
		&i.GeneratedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listVouchers = `-- name: ListVouchers :many
SELECT id, code, plan_id, status, used_by, used_at, generated_by, created_at FROM vouchers ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListVouchersParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListVouchers(ctx context.Context, arg ListVouchersParams) ([]Voucher, error) {
	rows, err := q.db.QueryContext(ctx, listVouchers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voucher
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.PlanID,
			&i.Status,
			&i.UsedBy,
			&i.UsedAt,
			&i.GeneratedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVouchers = `-- name: SearchVouchers :many
SELECT id, code, plan_id, status, used_by, used_at, generated_by, created_at FROM vouchers WHERE code LIKE '%' || CAST(?1 AS TEXT) || '%' ORDER BY id DESC LIMIT ?3 OFFSET ?2
`

type SearchVouchersParams struct {
	Q          string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) SearchVouchers(ctx context.Context, arg SearchVouchersParams) ([]Voucher, error) {
	rows, err := q.db.QueryContext(ctx, searchVouchers, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voucher
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.PlanID,
			&i.Status,
			&i.UsedBy,
			&i.UsedAt,
			&i.GeneratedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useVoucher = `-- name: UseVoucher :execrows
UPDATE vouchers SET status = 'used', used_by = ?, used_at = unixepoch()
WHERE id = ? AND status = 'unused'
`

type UseVoucherParams struct {
	UsedBy sql.NullInt64
	ID     int64
}

// Returns 1 if claimed, 0 if already used or missing.
func (q *Queries) UseVoucher(ctx context.Context, arg UseVoucherParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useVoucher, arg.UsedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
