// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: widgets.sql

package db

import (
	"context"
)

const listExpiringSubscriptions = `-- name: ListExpiringSubscriptions :many
SELECT s.id, s.customer_id, s.expires_at, s.status, c.username, c.fullname, p.name AS plan_name
FROM subscriptions s
JOIN customers c ON c.id = s.customer_id
JOIN plans p ON p.id = s.plan_id
WHERE s.status IN ('active', 'expired') AND s.expires_at >= ?1
ORDER BY s.expires_at, s.id LIMIT ?2
`

type ListExpiringSubscriptionsParams struct {
	Since     int64
	PageLimit int64
}

type ListExpiringSubscriptionsRow struct {
	ID         int64
	CustomerID int64
	ExpiresAt  int64
	Status     string
	Username   string
	Fullname   string
	PlanName   string
}

// Active or just-expired subscriptions, soonest expiry first (dashboard widget).
func (q *Queries) ListExpiringSubscriptions(ctx context.Context, arg ListExpiringSubscriptionsParams) ([]ListExpiringSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringSubscriptions, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringSubscriptionsRow
	for rows.Next() {
		var i ListExpiringSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ExpiresAt,
			&i.Status,
			&i.Username,
			&i.Fullname,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voucherStockByPlan = `-- name: VoucherStockByPlan :many
SELECT p.id, p.name,
  COUNT(CASE WHEN v.status = 'unused' THEN 1 END) AS unused,
  COUNT(CASE WHEN v.status = 'used' THEN 1 END) AS used
FROM plans p
LEFT JOIN vouchers v ON v.plan_id = p.id
GROUP BY p.id, p.name
ORDER BY p.name
`

type VoucherStockByPlanRow struct {
	ID     int64
	Name   string
	Unused int64
	Used   int64
}

func (q *Queries) VoucherStockByPlan(ctx context.Context) ([]VoucherStockByPlanRow, error) {
	rows, err := q.db.QueryContext(ctx, voucherStockByPlan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoucherStockByPlanRow
	for rows.Next() {
		var i VoucherStockByPlanRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unused,
			&i.Used,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
